// Single source of truth for design tokens: DTCG JSON in this dir →
// src/styles/tokens.css (generated; do not edit). Primitives land on :root;
// semantic `theme.*` tokens are emitted per theme. Light is the default; dark
// applies via [data-theme="dark"] or the OS preference when no override is set.
import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tmp = join(here, '.out');
const target = join(here, '..', 'src', 'styles', 'tokens.css');

async function build(name, sources, filter, selector) {
  const sd = new StyleDictionary({
    source: sources.map((s) => join(here, s)),
    log: { verbosity: 'silent' },
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: `${tmp}/`,
        files: [{
          destination: `${name}.css`,
          format: 'css/variables',
          filter,
          options: { selector, outputReferences: false, showFileHeader: false },
        }],
      },
    },
  });
  await sd.buildAllPlatforms();
  return readFileSync(join(tmp, `${name}.css`), 'utf8').trim();
}

const isTheme = (t) => t.path[0] === 'theme';
const prim = await build('primitives', ['primitives.tokens.json'], (t) => !isTheme(t), ':root');
const light = await build('light', ['primitives.tokens.json', 'light.tokens.json'], isTheme, ':root, [data-theme="light"]');
const darkForced = await build('dark', ['primitives.tokens.json', 'dark.tokens.json'], isTheme, '[data-theme="dark"]');
const darkBody = darkForced.replace(/^\[data-theme="dark"\] \{\n/, '').replace(/\n\}$/, '');
const darkAuto = `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${darkBody.replace(/^/gm, '  ')}\n  }\n}`;

mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, [
  '/* GENERATED by web/tokens/build.mjs from web/tokens/*.tokens.json — do not edit. */',
  prim, light, darkForced, darkAuto,
  ':root { color-scheme: light dark; }',
  '[data-theme="light"] { color-scheme: light; }',
  '[data-theme="dark"] { color-scheme: dark; }',
  '',
].join('\n\n'));
console.log(`tokens → ${target}`);
