// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CardDiffData, CardDiffErrors, CardDiffFamiliesData, CardDiffFamiliesResponses, CardDiffResponses, CommandersData, CommandersErrors, CommandersResponses, CompareData, CompareErrors, CompareResponses, GetJobData, GetJobErrors, GetJobResponses, JobEventsData, JobEventsErrors, JobEventsResponses, JobSpecsData, JobSpecsResponses, ListJobsData, ListJobsResponses, SubmitJobData, SubmitJobErrors, SubmitJobResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Job Specs
 */
export const jobSpecs = <ThrowOnError extends boolean = false>(options?: Options<JobSpecsData, ThrowOnError>): RequestResult<JobSpecsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<JobSpecsResponses, unknown, ThrowOnError>({ url: '/api/jobs/specs', ...options });

/**
 * Submit Job
 */
export const submitJob = <ThrowOnError extends boolean = false>(options: Options<SubmitJobData, ThrowOnError>): RequestResult<SubmitJobResponses, SubmitJobErrors, ThrowOnError> => (options.client ?? client).post<SubmitJobResponses, SubmitJobErrors, ThrowOnError>({
    url: '/api/jobs/{name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Jobs
 */
export const listJobs = <ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>): RequestResult<ListJobsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({ url: '/api/jobs', ...options });

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/api/jobs/{job_id}', ...options });

/**
 * Job Events
 */
export const jobEvents = <ThrowOnError extends boolean = false>(options: Options<JobEventsData, ThrowOnError, unknown>): Promise<ServerSentEventsResult<JobEventsResponses>> => (options.client ?? client).sse.get<JobEventsResponses, JobEventsErrors, ThrowOnError>({ url: '/api/jobs/{job_id}/events', ...options });

/**
 * Commanders
 */
export const commanders = <ThrowOnError extends boolean = false>(options: Options<CommandersData, ThrowOnError>): RequestResult<CommandersResponses, CommandersErrors, ThrowOnError> => (options.client ?? client).get<CommandersResponses, CommandersErrors, ThrowOnError>({ url: '/api/edhrec/commanders', ...options });

/**
 * Compare
 */
export const compare = <ThrowOnError extends boolean = false>(options: Options<CompareData, ThrowOnError>): RequestResult<CompareResponses, CompareErrors, ThrowOnError> => (options.client ?? client).get<CompareResponses, CompareErrors, ThrowOnError>({ url: '/api/edhrec/compare', ...options });

/**
 * Card Diff Families
 */
export const cardDiffFamilies = <ThrowOnError extends boolean = false>(options?: Options<CardDiffFamiliesData, ThrowOnError>): RequestResult<CardDiffFamiliesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CardDiffFamiliesResponses, unknown, ThrowOnError>({ url: '/api/card-diff/families', ...options });

/**
 * Card Diff
 */
export const cardDiff = <ThrowOnError extends boolean = false>(options: Options<CardDiffData, ThrowOnError>): RequestResult<CardDiffResponses, CardDiffErrors, ThrowOnError> => (options.client ?? client).get<CardDiffResponses, CardDiffErrors, ThrowOnError>({ url: '/api/card-diff', ...options });
