// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, ServerSentEventsResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CollectionBuyListData, CollectionBuyListErrors, CollectionBuyListResponses, CollectionData, CollectionErrors, CollectionFamiliesData, CollectionFamiliesResponses, CollectionResponses, CommandersData, CommandersErrors, CommandersResponses, CompareData, CompareErrors, CompareResponses, DeckDetailData, DeckDetailErrors, DeckDetailResponses, DeckListData, DeckListResponses, GetJobData, GetJobErrors, GetJobResponses, IngestCommitData, IngestCommitErrors, IngestCommitResponses, IngestPreconsData, IngestPreconsErrors, IngestPreconsResponses, IngestResolveData, IngestResolveErrors, IngestResolveResponses, IngestSearchData, IngestSearchErrors, IngestSearchResponses, JobEventsData, JobEventsErrors, JobEventsResponses, JobSpecsData, JobSpecsResponses, ListJobsData, ListJobsResponses, SubmitJobData, SubmitJobErrors, SubmitJobResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Job Specs
 */
export const jobSpecs = <ThrowOnError extends boolean = false>(options?: Options<JobSpecsData, ThrowOnError>): RequestResult<JobSpecsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<JobSpecsResponses, unknown, ThrowOnError>({ url: '/api/jobs/specs', ...options });

/**
 * Submit Job
 */
export const submitJob = <ThrowOnError extends boolean = false>(options: Options<SubmitJobData, ThrowOnError>): RequestResult<SubmitJobResponses, SubmitJobErrors, ThrowOnError> => (options.client ?? client).post<SubmitJobResponses, SubmitJobErrors, ThrowOnError>({
    url: '/api/jobs/{name}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Jobs
 */
export const listJobs = <ThrowOnError extends boolean = false>(options?: Options<ListJobsData, ThrowOnError>): RequestResult<ListJobsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListJobsResponses, unknown, ThrowOnError>({ url: '/api/jobs', ...options });

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/api/jobs/{job_id}', ...options });

/**
 * Job Events
 */
export const jobEvents = <ThrowOnError extends boolean = false>(options: Options<JobEventsData, ThrowOnError, unknown>): Promise<ServerSentEventsResult<JobEventsResponses>> => (options.client ?? client).sse.get<JobEventsResponses, JobEventsErrors, ThrowOnError>({ url: '/api/jobs/{job_id}/events', ...options });

/**
 * Commanders
 */
export const commanders = <ThrowOnError extends boolean = false>(options: Options<CommandersData, ThrowOnError>): RequestResult<CommandersResponses, CommandersErrors, ThrowOnError> => (options.client ?? client).get<CommandersResponses, CommandersErrors, ThrowOnError>({ url: '/api/edhrec/commanders', ...options });

/**
 * Compare
 */
export const compare = <ThrowOnError extends boolean = false>(options: Options<CompareData, ThrowOnError>): RequestResult<CompareResponses, CompareErrors, ThrowOnError> => (options.client ?? client).get<CompareResponses, CompareErrors, ThrowOnError>({ url: '/api/edhrec/compare', ...options });

/**
 * Collection Families
 */
export const collectionFamilies = <ThrowOnError extends boolean = false>(options?: Options<CollectionFamiliesData, ThrowOnError>): RequestResult<CollectionFamiliesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CollectionFamiliesResponses, unknown, ThrowOnError>({ url: '/api/collection/families', ...options });

/**
 * Collection
 */
export const collection = <ThrowOnError extends boolean = false>(options: Options<CollectionData, ThrowOnError>): RequestResult<CollectionResponses, CollectionErrors, ThrowOnError> => (options.client ?? client).get<CollectionResponses, CollectionErrors, ThrowOnError>({ url: '/api/collection', ...options });

/**
 * Collection Buy List
 */
export const collectionBuyList = <ThrowOnError extends boolean = false>(options: Options<CollectionBuyListData, ThrowOnError>): RequestResult<CollectionBuyListResponses, CollectionBuyListErrors, ThrowOnError> => (options.client ?? client).post<CollectionBuyListResponses, CollectionBuyListErrors, ThrowOnError>({
    url: '/api/collection/buy-list',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Deck List
 */
export const deckList = <ThrowOnError extends boolean = false>(options?: Options<DeckListData, ThrowOnError>): RequestResult<DeckListResponses, unknown, ThrowOnError> => (options?.client ?? client).get<DeckListResponses, unknown, ThrowOnError>({ url: '/api/decks', ...options });

/**
 * Deck Detail
 */
export const deckDetail = <ThrowOnError extends boolean = false>(options: Options<DeckDetailData, ThrowOnError>): RequestResult<DeckDetailResponses, DeckDetailErrors, ThrowOnError> => (options.client ?? client).get<DeckDetailResponses, DeckDetailErrors, ThrowOnError>({ url: '/api/decks/{slug}', ...options });

/**
 * Ingest Search
 */
export const ingestSearch = <ThrowOnError extends boolean = false>(options: Options<IngestSearchData, ThrowOnError>): RequestResult<IngestSearchResponses, IngestSearchErrors, ThrowOnError> => (options.client ?? client).get<IngestSearchResponses, IngestSearchErrors, ThrowOnError>({ url: '/api/ingest/search', ...options });

/**
 * Ingest Resolve
 */
export const ingestResolve = <ThrowOnError extends boolean = false>(options: Options<IngestResolveData, ThrowOnError>): RequestResult<IngestResolveResponses, IngestResolveErrors, ThrowOnError> => (options.client ?? client).post<IngestResolveResponses, IngestResolveErrors, ThrowOnError>({
    url: '/api/ingest/resolve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ingest Commit
 */
export const ingestCommit = <ThrowOnError extends boolean = false>(options: Options<IngestCommitData, ThrowOnError>): RequestResult<IngestCommitResponses, IngestCommitErrors, ThrowOnError> => (options.client ?? client).post<IngestCommitResponses, IngestCommitErrors, ThrowOnError>({
    url: '/api/ingest/commit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Ingest Precons
 */
export const ingestPrecons = <ThrowOnError extends boolean = false>(options?: Options<IngestPreconsData, ThrowOnError>): RequestResult<IngestPreconsResponses, IngestPreconsErrors, ThrowOnError> => (options?.client ?? client).get<IngestPreconsResponses, IngestPreconsErrors, ThrowOnError>({ url: '/api/ingest/precons', ...options });
