// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ActionOut
 */
export type ActionOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Summary
     */
    summary: string;
};

/**
 * BracketOut
 */
export type BracketOut = {
    /**
     * Suggested Bracket
     *
     * Floor (1–4) from Wizards' bracket criteria; None without a commander. Never authoritative.
     */
    suggested_bracket: number | null;
    /**
     * Game Changer Count
     */
    game_changer_count: number;
    /**
     * Game Changers
     */
    game_changers: Array<string>;
    /**
     * Mass Land Denial
     */
    mass_land_denial: Array<string>;
    /**
     * Extra Turns
     */
    extra_turns: Array<string>;
    /**
     * Two Card Combos
     */
    two_card_combos: number;
    /**
     * Rationale
     */
    rationale: Array<string>;
    /**
     * Stale Data
     */
    stale_data: boolean;
    /**
     * Spellbook Available
     */
    spellbook_available: boolean;
};

/**
 * BuildIn
 */
export type BuildIn = {
    /**
     * Allow Shortfall
     *
     * Pledge what's free even if some cards are missing.
     */
    allow_shortfall?: boolean;
};

/**
 * BuildPlanOut
 */
export type BuildPlanOut = {
    /**
     * Target
     *
     * The copy a build would assemble; null when every copy is built.
     */
    target: string | null;
    /**
     * Need
     */
    need: number;
    /**
     * Covered
     *
     * Copies of `need` you have free.
     */
    covered: number;
    /**
     * Short
     */
    short: Array<SwapLineOut>;
};

/**
 * BuyItem
 */
export type BuyItem = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Qty
     */
    qty?: number;
};

/**
 * BuyListIn
 */
export type BuyListIn = {
    /**
     * Target
     */
    target: 'manapool' | 'tcgplayer' | 'cardkingdom' | 'moxfield' | 'plain';
    /**
     * Items
     */
    items: Array<BuyItem>;
};

/**
 * BuyListOut
 */
export type BuyListOut = {
    /**
     * Text
     */
    text: string;
    /**
     * Lines
     */
    lines: number;
};

/**
 * CardCombosOut
 */
export type CardCombosOut = {
    /**
     * Available
     */
    available: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Combos
     */
    combos: Array<ComboOut>;
};

/**
 * CardExploreOut
 */
export type CardExploreOut = {
    a: CardProfileOut;
    b?: CardProfileOut | null;
    /**
     * Commanders
     *
     * Comparison only: by share.
     */
    commanders?: Array<PairedOut>;
    /**
     * Coplayed
     *
     * Comparison only: by lift.
     */
    coplayed?: Array<PairedOut>;
    /**
     * Tags
     *
     * Comparison only: a_only / both / b_only.
     */
    tags?: {
        [key: string]: Array<OracleTagOut>;
    };
};

/**
 * CardOptionOut
 */
export type CardOptionOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Cached
     *
     * EDHREC card page already cached locally.
     */
    cached: boolean;
    /**
     * Commander Eligible
     */
    commander_eligible: boolean;
};

/**
 * CardPriceOut
 */
export type CardPriceOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Collector Number
     */
    collector_number: string;
    /**
     * Rarity
     */
    rarity: string;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Finishes
     */
    finishes: Array<string>;
    /**
     * Treatment
     */
    treatment: string;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Is Chase
     */
    is_chase: boolean;
    /**
     * Price Usd
     */
    price_usd: number | null;
    /**
     * Price Usd Foil
     */
    price_usd_foil: number | null;
    /**
     * Floor Usd
     *
     * Cheapest nonfoil printing of this card anywhere.
     */
    floor_usd?: number | null;
    /**
     * Floor Set Code
     */
    floor_set_code?: string | null;
    /**
     * Floor Collector Number
     */
    floor_collector_number?: string | null;
    /**
     * Owned
     */
    owned: number;
};

/**
 * CardProfileOut
 */
export type CardProfileOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    facts: FactsOut;
    /**
     * Commander Eligible
     */
    commander_eligible: boolean;
    /**
     * Num Decks
     */
    num_decks: number | null;
    /**
     * Potential Decks
     */
    potential_decks: number | null;
    /**
     * Salt
     */
    salt: number | null;
    /**
     * Functions
     */
    functions: Array<string>;
    /**
     * Tags
     */
    tags: Array<OracleTagOut>;
    /**
     * Commanders
     */
    commanders: Array<EntryOut>;
    /**
     * Coplayed
     */
    coplayed: Array<EntryOut>;
    /**
     * Similar
     */
    similar: Array<EntryOut>;
    /**
     * Deck Mix
     */
    deck_mix: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * CardSourceOut
 */
export type CardSourceOut = {
    source: SourceOut;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Copies
     *
     * Copies acquired from this source (history: may exceed what is owned today).
     */
    copies: number;
    /**
     * Acquisitions
     *
     * Separate ingests from this source (e.g. 2 = two purchases of the same product).
     */
    acquisitions?: number;
};

/**
 * CartAuditOut
 */
export type CartAuditOut = {
    /**
     * Lines
     */
    lines: number;
    /**
     * Copies
     */
    copies: number;
    /**
     * Total
     */
    total: number;
    /**
     * Unidentified
     */
    unidentified: Array<UnidentifiedOut>;
    /**
     * Family
     */
    family: string | null;
    /**
     * Families
     */
    families: Array<string>;
    /**
     * Dupes
     */
    dupes: Array<DupeOut>;
    /**
     * Owned
     */
    owned: Array<OwnedOut>;
    /**
     * Missing
     */
    missing: Array<MissingOut>;
    /**
     * Overpay
     */
    overpay: Array<OverpayOut>;
};

/**
 * CartIn
 */
export type CartIn = {
    /**
     * Family
     *
     * Set family to check gaps against; imputed when the cart sits in one.
     */
    family?: string | null;
};

/**
 * CartSetupOut
 */
export type CartSetupOut = {
    /**
     * Account
     *
     * MANAPOOL_EMAIL, _PASSWORD and _ACCESS_TOKEN are configured, so the cart can be read directly.
     */
    account: boolean;
};

/**
 * ChangeOut
 */
export type ChangeOut = {
    printing: PrintingOut;
    /**
     * Board
     */
    board: string;
    /**
     * Finish
     */
    finish: string;
    /**
     * Before
     */
    before: number;
    /**
     * After
     */
    after: number;
};

/**
 * CheckIn
 */
export type CheckIn = {
    /**
     * Cards
     */
    cards: Array<DraftCardIn>;
    /**
     * Combos
     *
     * Also ask Commander Spellbook for two-card combos (network).
     */
    combos?: boolean;
};

/**
 * CheckOut
 */
export type CheckOut = {
    /**
     * Format
     */
    format: string;
    legality: LegalityOut;
    bracket: BracketOut | null;
};

/**
 * ChecklistIn
 */
export type ChecklistIn = {
    /**
     * Family
     *
     * Family label for the ingest event, e.g. 'Final Fantasy'.
     */
    family: string;
    /**
     * Changes
     */
    changes: Array<CountIn>;
};

/**
 * ChecklistOut
 */
export type ChecklistOut = {
    /**
     * Ingest Id
     *
     * The checklist ingest event; null when nothing changed.
     */
    ingest_id: number | null;
    /**
     * Added
     */
    added: number;
    /**
     * Updated
     */
    updated: number;
    /**
     * Zeroed
     */
    zeroed: number;
    /**
     * Copies Added
     */
    copies_added: number;
    /**
     * Copies Removed
     */
    copies_removed: number;
    /**
     * Rows
     */
    rows: Array<CountRowOut>;
};

/**
 * CollectionCardOut
 */
export type CollectionCardOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Family
     */
    family: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Collector Number
     */
    collector_number: string;
    /**
     * Rarity
     */
    rarity: string;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Released At
     */
    released_at: string | null;
    /**
     * Finishes
     */
    finishes: Array<string>;
    /**
     * Owned
     *
     * finish -> owned copies
     */
    owned: {
        [key: string]: number;
    };
    /**
     * Pledged
     *
     * finish -> copies pledged to built decks
     */
    pledged: {
        [key: string]: number;
    };
    /**
     * Price Usd
     */
    price_usd: number | null;
    /**
     * Price Usd Foil
     */
    price_usd_foil: number | null;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url: string | null;
    /**
     * Treatment
     *
     * Treatment codes (b, fa, shw, ext, sm, ff; '|'-joined); '' = plain
     */
    treatment: string;
    /**
     * Standard Frame
     */
    standard_frame: boolean;
    /**
     * Is Bulk
     */
    is_bulk: boolean;
    /**
     * Is Chase
     */
    is_chase: boolean;
    /**
     * Functions
     *
     * Function root keys (Scryfall Tagger roll-up).
     */
    functions?: Array<string>;
    /**
     * Card Owned
     *
     * Copies of this card owned in any printing, any set.
     */
    card_owned?: number;
    /**
     * Sources
     *
     * Source keys this owned printing's copies were acquired from (see CollectionOut.sources).
     */
    sources?: Array<string>;
};

/**
 * CollectionOut
 */
export type CollectionOut = {
    /**
     * Families
     */
    families: Array<FamilySummaryOut>;
    /**
     * Cards
     */
    cards: Array<CollectionCardOut>;
    /**
     * Skipped
     *
     * Codes that didn't resolve to a family.
     */
    skipped?: Array<string>;
    /**
     * Functions
     *
     * Function roots, display order.
     */
    functions?: Array<FunctionRootOut>;
    /**
     * Sources
     *
     * Every source behind an owned printing in this view, most printings first.
     */
    sources?: Array<SourceOut>;
};

/**
 * ColorOptionOut
 */
export type ColorOptionOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Label
     */
    label: string;
    /**
     * Colors
     *
     * WUBRG identity letters ('' = colorless).
     */
    colors: string;
};

/**
 * ComboOut
 */
export type ComboOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Url
     *
     * The combo's page on Commander Spellbook.
     */
    url: string;
    /**
     * Pieces
     */
    pieces: Array<PieceOut>;
    /**
     * Produces
     *
     * What it does (e.g. 'Infinite colorless mana').
     */
    produces: Array<string>;
    /**
     * Requires
     *
     * Extra pieces described, not named (any card that fits).
     */
    requires: Array<string>;
    /**
     * Description
     *
     * Steps, one per line.
     */
    description: string;
    /**
     * Prerequisites
     */
    prerequisites: string;
    /**
     * Mana Needed
     */
    mana_needed: string;
    /**
     * Popularity
     *
     * Decks on EDHREC running every piece.
     */
    popularity: number | null;
    /**
     * Identity
     */
    identity: string;
    /**
     * One-card-away combos: the card to add.
     */
    missing?: PieceOut | null;
};

/**
 * CommanderOption
 */
export type CommanderOption = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Cached
     *
     * EDHREC commander page already in the local cache.
     */
    cached: boolean;
};

/**
 * CommitIn
 */
export type CommitIn = {
    /**
     * Items
     */
    items: Array<CommitItem>;
    /**
     * Source
     */
    source: 'search' | 'paste' | 'deck';
    /**
     * Label
     *
     * Free text recorded on the ingest event (e.g. a deck name).
     */
    label?: string | null;
};

/**
 * CommitItem
 */
export type CommitItem = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Qty
     */
    qty: number;
};

/**
 * CommitOut
 */
export type CommitOut = {
    /**
     * Ingest Id
     */
    ingest_id: number;
    /**
     * Copies
     */
    copies: number;
    /**
     * Printings
     */
    printings: number;
    /**
     * Summary
     */
    summary: string;
};

/**
 * CompareCardOut
 */
export type CompareCardOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * A Pct
     */
    a_pct: number | null;
    /**
     * B Pct
     */
    b_pct: number | null;
    /**
     * A Decks
     */
    a_decks: number | null;
    /**
     * B Decks
     */
    b_decks: number | null;
    /**
     * Delta
     */
    delta: number | null;
    /**
     * Synergy A
     */
    synergy_a: number | null;
    /**
     * Synergy B
     */
    synergy_b: number | null;
    /**
     * Trend A
     */
    trend_a: number | null;
    /**
     * Trend B
     */
    trend_b: number | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Mana Cost
     */
    mana_cost: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string> | null;
    /**
     * Rarity
     */
    rarity: string | null;
    /**
     * Lowest Usd
     */
    lowest_usd: number | null;
    /**
     * Lowest Usd Foil
     */
    lowest_usd_foil: number | null;
    /**
     * Scryfall Id
     */
    scryfall_id: string | null;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Set Code
     */
    set_code: string | null;
    /**
     * Collector Number
     */
    collector_number: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url: string | null;
    /**
     * Functions
     *
     * Function root keys (Scryfall Tagger roll-up).
     */
    functions?: Array<string>;
    /**
     * Oracle Tags
     *
     * Top Tagger oracle tags by weight.
     */
    oracle_tags?: Array<OracleTagOut>;
    /**
     * Owned
     *
     * Copies you own across every printing.
     */
    owned?: number;
    /**
     * Free
     *
     * Owned copies no built deck has pledged.
     */
    free?: number;
};

/**
 * CompareOut
 */
export type CompareOut = {
    /**
     * Name A
     */
    name_a: string;
    /**
     * Name B
     *
     * None when exploring one commander.
     */
    name_b?: string | null;
    /**
     * Slug A
     */
    slug_a: string;
    /**
     * Slug B
     */
    slug_b?: string | null;
    /**
     * Cards
     */
    cards: Array<CompareCardOut>;
    /**
     * Functions
     *
     * Function roots, display order.
     */
    functions?: Array<FunctionRootOut>;
};

/**
 * ConfirmIn
 */
export type ConfirmIn = {
    /**
     * Url
     */
    url: string;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
    /**
     * Available
     */
    available?: boolean | null;
    /**
     * What the listing is; null forgets a confirmation.
     */
    choice: MatchOut | null;
};

/**
 * CopyIn
 */
export type CopyIn = {
    /**
     * Name
     */
    name?: string | null;
};

/**
 * CountIn
 */
export type CountIn = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Qty
     */
    qty: number;
    /**
     * Expected
     *
     * Count the editor started from; refused (409) if the collection moved since.
     */
    expected?: number | null;
};

/**
 * CountRowOut
 */
export type CountRowOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: string;
    /**
     * Old Qty
     */
    old_qty: number;
    /**
     * New Qty
     */
    new_qty: number;
};

/**
 * DeckCardOut
 */
export type DeckCardOut = {
    printing: PrintingOut;
    /**
     * Board
     */
    board: 'main' | 'side' | 'commander' | 'companion' | 'maybe' | 'token';
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil' | 'either';
    /**
     * Count
     */
    count: number;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Pledged Here
     *
     * Copies of this printing pledged to THIS deck (any finish).
     */
    pledged_here: number;
    /**
     * Free
     *
     * Copies you own that no deck has pledged (any finish).
     */
    free: number;
};

/**
 * DeckCombosOut
 */
export type DeckCombosOut = {
    /**
     * Available
     *
     * False when Commander Spellbook couldn't be reached; see `error`.
     */
    available: boolean;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Identity
     */
    identity?: string | null;
    /**
     * Included
     */
    included: Array<ComboOut>;
    /**
     * Almost
     *
     * Combos one card away, in the deck's colours.
     */
    almost: Array<ComboOut>;
    /**
     * Missing Cards
     *
     * The near-misses rolled up per missing card, most combos first.
     */
    missing_cards: Array<MissingCardOut>;
    /**
     * Off Color
     *
     * Near-misses that would need another colour (not listed).
     */
    off_color: number;
};

/**
 * DeckCostOut
 */
export type DeckCostOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Sealed Product
     *
     * The sealed product this precon ships in.
     */
    sealed_product?: string | null;
    /**
     * Sealed
     */
    sealed: number | null;
    /**
     * Scratch
     *
     * Every card new, exact printings.
     */
    scratch?: number | null;
    /**
     * With Collection
     *
     * Your free cards first, buy the rest (exact).
     */
    with_collection?: number | null;
    /**
     * Scratch Floor
     */
    scratch_floor: number;
    /**
     * With Collection Floor
     */
    with_collection_floor: number;
    /**
     * Coverage
     */
    coverage: number;
    /**
     * Unpriced
     */
    unpriced: number;
    /**
     * Total Need
     */
    total_need: number;
    /**
     * Lines
     */
    lines: Array<DeckLineOut>;
};

/**
 * DeckDetailOut
 */
export type DeckDetailOut = {
    deck: DeckSummaryOut;
    /**
     * Cards
     */
    cards: Array<DeckCardOut>;
    /**
     * Version Id
     *
     * Current version; pass back as expected_version_id when saving.
     */
    version_id: number;
    /**
     * Editable
     *
     * False for precons (read-only recipes): copy the deck to edit it.
     */
    editable: boolean;
};

/**
 * DeckLineOut
 */
export type DeckLineOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: string;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Collector Number
     */
    collector_number: string;
    /**
     * Need
     */
    need: number;
    /**
     * Free
     */
    free: number;
    /**
     * Buy
     */
    buy: number;
    /**
     * Unit Usd
     */
    unit_usd: number | null;
    /**
     * Floor Usd
     */
    floor_usd: number | null;
    /**
     * Floor Set Code
     */
    floor_set_code?: string | null;
    /**
     * Floor Collector Number
     */
    floor_collector_number?: string | null;
    /**
     * Floor Scryfall Id
     *
     * The cheapest printing (this one when unpriced elsewhere).
     */
    floor_scryfall_id: string;
    /**
     * Bonus
     *
     * A Secret Lair drop's bonus card (shipped with the drop, not in its decklist).
     */
    bonus?: boolean;
};

/**
 * DeckPledgeOut
 */
export type DeckPledgeOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Count
     */
    count: number;
};

/**
 * DeckSourceOut
 *
 * A fetched deck as the builder returned it — pass back to save it as a decklist.
 */
export type DeckSourceOut = {
    /**
     * Source
     */
    source?: string | null;
    /**
     * Id
     */
    id?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Author
     */
    author?: string | null;
    /**
     * Cards
     */
    cards?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * DeckSummaryOut
 */
export type DeckSummaryOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Format
     */
    format: string | null;
    /**
     * Deck Type
     *
     * What kind of deck: the game format (Commander, Standard, Pauper, Jumpstart…), else the precon product family (Starter / intro, Secret Lair, Land pack…).
     */
    deck_type: string;
    /**
     * State
     *
     * 'built' when at least one copy is built, else 'deconstructed'.
     */
    state: 'built' | 'deconstructed';
    /**
     * Built
     *
     * Copies of this recipe kept assembled (cards pledged).
     */
    built: number;
    /**
     * Slugs
     *
     * Every deck row that is a copy of this recipe; `slug` is the representative (a built copy first).
     */
    slugs: Array<string>;
    /**
     * Origin
     *
     * precon = MTGJSON product; import = deck-builder URL; custom = hand-built.
     */
    origin: 'precon' | 'import' | 'custom';
    /**
     * Source
     *
     * Deck builder for imports (moxfield, archidekt…); precon product type for precons.
     */
    source: string | null;
    /**
     * Author
     */
    author: string | null;
    /**
     * Set Code
     */
    set_code: string | null;
    /**
     * Set Name
     */
    set_name: string | null;
    /**
     * Released
     *
     * Product release date (precons) or set release date; ISO.
     */
    released: string | null;
    /**
     * Cards
     *
     * Card count excluding tokens.
     */
    cards: number;
    /**
     * Value Usd
     *
     * Sum of non-token cards at their finish's price.
     */
    value_usd: number;
    /**
     * Pledged Pct
     *
     * Share of non-token card copies currently pledged to this deck (0–100).
     */
    pledged_pct: number;
    /**
     * Image Uri
     *
     * Representative art: the commander, else the priciest card.
     */
    image_uri: string | null;
};

/**
 * DraftCardIn
 */
export type DraftCardIn = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Board
     */
    board: 'main' | 'side' | 'commander' | 'companion' | 'maybe' | 'token';
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil' | 'either';
    /**
     * Count
     */
    count: number;
};

/**
 * DraftCombosIn
 */
export type DraftCombosIn = {
    /**
     * Cards
     */
    cards: Array<DraftCardIn>;
};

/**
 * DraftIn
 */
export type DraftIn = {
    /**
     * Cards
     */
    cards: Array<DraftCardIn>;
};

/**
 * DupeOut
 */
export type DupeOut = {
    /**
     * Scryfall Id
     */
    scryfall_id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set
     */
    set: string;
    /**
     * Num
     */
    num: string;
    /**
     * Fin
     */
    fin?: string;
    /**
     * Nf Qty
     */
    nf_qty: number;
    /**
     * Fo Qty
     */
    fo_qty: number;
    /**
     * Nf Price
     */
    nf_price: number | null;
    /**
     * Fo Price
     */
    fo_price: number | null;
    /**
     * Cheaper
     */
    cheaper: number | null;
    /**
     * Note
     */
    note: string;
};

/**
 * EntryOut
 */
export type EntryOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    facts: FactsOut;
    /**
     * Num Decks
     */
    num_decks?: number | null;
    /**
     * Potential Decks
     */
    potential_decks?: number | null;
    /**
     * Share
     *
     * % of the potential decks that run it.
     */
    share?: number | null;
    /**
     * Lift
     *
     * Co-play: how many times more often than chance.
     */
    lift?: number | null;
    /**
     * Group
     *
     * Co-play type group, or 'top'/'new' for commanders.
     */
    group?: string | null;
};

/**
 * FactsOut
 */
export type FactsOut = {
    /**
     * Oracle Id
     */
    oracle_id?: string | null;
    /**
     * Type Line
     */
    type_line?: string | null;
    /**
     * Cmc
     */
    cmc?: number | null;
    /**
     * Color Identity
     */
    color_identity?: Array<string>;
    /**
     * Lowest Usd
     */
    lowest_usd?: number | null;
    /**
     * Scryfall Id
     */
    scryfall_id?: string | null;
    /**
     * Image Uri
     */
    image_uri?: string | null;
    /**
     * Set Code
     */
    set_code?: string | null;
    /**
     * Collector Number
     */
    collector_number?: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url?: string | null;
    /**
     * Owned
     */
    owned?: number;
    /**
     * Free
     */
    free?: number;
};

/**
 * FamilyCardsOut
 */
export type FamilyCardsOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Cards
     */
    cards: Array<CardPriceOut>;
};

/**
 * FamilyOption
 */
export type FamilyOption = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * FamilyProductsOut
 */
export type FamilyProductsOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Products
     */
    products: Array<ProductOut>;
};

/**
 * FamilySummaryOut
 */
export type FamilySummaryOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Printings
     */
    printings: number;
    /**
     * Owned Printings
     */
    owned_printings: number;
    /**
     * Owned Copies
     */
    owned_copies: number;
    /**
     * Owned Usd
     */
    owned_usd: number;
    /**
     * Missing Printings
     */
    missing_printings: number;
    /**
     * Missing Usd
     */
    missing_usd: number;
    /**
     * Sets
     *
     * Member sets with printings, oldest first.
     */
    sets?: Array<SetRefOut>;
};

/**
 * FeaturesOut
 */
export type FeaturesOut = {
    /**
     * Flags
     */
    flags: {
        [key: string]: boolean;
    };
};

/**
 * FunctionRootOut
 *
 * A curated function root (``config/function_tags.toml``), in display order.
 */
export type FunctionRootOut = {
    /**
     * Key
     */
    key: string;
    /**
     * Label
     */
    label: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HistoryEntryOut
 */
export type HistoryEntryOut = {
    /**
     * Ingest Id
     */
    ingest_id: number;
    /**
     * At
     *
     * ISO timestamp of the ingest.
     */
    at: string;
    /**
     * Method
     */
    method: string;
    /**
     * Kind
     *
     * deck = playable product; pool = card pool (land pack, scene box, Secret Lair…); singles = cards added individually; checklist = a bulk checklist ingest (source product not recorded); unknown = reconstructed bucket with no known source; move = cards pledged to / released from a deck.
     */
    kind: 'deck' | 'pool' | 'singles' | 'checklist' | 'unknown' | 'move';
    /**
     * Title
     */
    title: string;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Dated
     *
     * acquired = when you added it; identified = when Find products attributed loose cards to it; reconstructed = the V19 backfill.
     */
    dated: 'acquired' | 'identified' | 'reconstructed';
    /**
     * Ledgered
     *
     * False for ingests before the ledger existed: their copies are counted in 'Checklists before the ledger' / the unknown buckets.
     */
    ledgered: boolean;
    /**
     * Copies In
     */
    copies_in: number;
    /**
     * Copies Out
     *
     * Copies later removed or re-attributed to an identified product.
     */
    copies_out: number;
    /**
     * Held
     *
     * Copies this entry still accounts for.
     */
    held: number;
    /**
     * Printings
     */
    printings: number;
    /**
     * Value Usd
     *
     * Held copies at today's prices.
     */
    value_usd: number;
    /**
     * Lines
     *
     * Rows the ingest touched (checklist rows, deck-move lines).
     */
    lines: number;
    /**
     * Product
     *
     * MTGJSON fileName for product entries.
     */
    product?: string | null;
    /**
     * Set Code
     */
    set_code?: string | null;
    /**
     * Deck Slug
     *
     * Deck to open: the moved deck, or the playable product's deck row.
     */
    deck_slug?: string | null;
};

/**
 * HistoryEventOut
 */
export type HistoryEventOut = {
    entry: HistoryEntryOut;
    /**
     * Lines
     */
    lines: Array<HistoryLineOut>;
};

/**
 * HistoryLineOut
 */
export type HistoryLineOut = {
    printing: PrintingOut;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Copies In
     */
    copies_in: number;
    /**
     * Copies Out
     */
    copies_out: number;
    /**
     * Held
     */
    held: number;
    /**
     * Unit Usd
     */
    unit_usd: number | null;
};

/**
 * HistoryOut
 */
export type HistoryOut = {
    /**
     * Entries
     */
    entries: Array<HistoryEntryOut>;
    /**
     * Prices As Of
     *
     * Newest local price fetch date (YYYY-MM-DD).
     */
    prices_as_of: string | null;
    /**
     * Stale Sets
     *
     * Set codes whose local prices are older than a week (not refreshed).
     */
    stale_sets: Array<string>;
};

/**
 * HoldingsOut
 */
export type HoldingsOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Owned
     *
     * finish -> owned copies
     */
    owned: {
        [key: string]: number;
    };
    /**
     * Pledged
     *
     * finish -> copies pledged to built decks
     */
    pledged: {
        [key: string]: number;
    };
    /**
     * Free
     *
     * finish -> owned copies no deck has pledged
     */
    free: {
        [key: string]: number;
    };
    /**
     * Decks
     */
    decks: Array<DeckPledgeOut>;
    /**
     * Sources
     */
    sources: Array<CardSourceOut>;
    /**
     * Other Printings Owned
     *
     * Copies of the same card owned in other printings (all finishes).
     */
    other_printings_owned: number;
};

/**
 * ImportIn
 */
export type ImportIn = {
    deck: DeckSourceOut;
    /**
     * Force
     *
     * Replace the cards of a deck already imported from this source.
     */
    force?: boolean;
};

/**
 * ImportOut
 */
export type ImportOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Duplicate
     *
     * Already imported from this source; `slug` is the existing deck.
     */
    duplicate: boolean;
    /**
     * Summary
     */
    summary: string;
};

/**
 * JobOut
 */
export type JobOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Inputs
     */
    inputs: {
        [key: string]: unknown;
    };
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Progress
     */
    progress: {
        [key: string]: unknown;
    } | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Artifacts
     */
    artifacts: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Error
     */
    error: string | null;
};

/**
 * JobSpecOut
 */
export type JobSpecOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Mutates
     */
    mutates: boolean;
    /**
     * Input Schema
     */
    input_schema: {
        [key: string]: unknown;
    };
};

/**
 * LegalityOut
 */
export type LegalityOut = {
    /**
     * Format
     */
    format: string;
    /**
     * Legal
     */
    legal: boolean;
    /**
     * Checked Count
     */
    checked_count: number;
    /**
     * Violations
     */
    violations: Array<ViolationOut>;
};

/**
 * MatchOut
 */
export type MatchOut = {
    /**
     * Kind
     */
    kind: 'sealed' | 'sld' | 'single';
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Scryfall Id
     */
    scryfall_id?: string | null;
    /**
     * Finish
     */
    finish?: string | null;
    /**
     * Price
     *
     * Singles: the printing's market at that finish.
     */
    price?: number | null;
};

/**
 * MissingCardOut
 */
export type MissingCardOut = {
    piece: PieceOut;
    /**
     * Combos
     *
     * Ids of the near-miss combos this card completes, most popular first.
     */
    combos: Array<string>;
    /**
     * Popularity
     */
    popularity: number;
};

/**
 * MissingOut
 */
export type MissingOut = {
    /**
     * Scryfall Id
     */
    scryfall_id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set
     */
    set: string;
    /**
     * Num
     */
    num: string;
    /**
     * Fin
     */
    fin: string;
    /**
     * Market
     */
    market: number | null;
};

/**
 * NewDeckIn
 */
export type NewDeckIn = {
    /**
     * Name
     */
    name: string;
    /**
     * Format
     */
    format?: string;
    /**
     * Commander
     *
     * scryfall_id of the commander to seed.
     */
    commander?: string | null;
};

/**
 * OpenTabsOut
 */
export type OpenTabsOut = {
    /**
     * Browser
     */
    browser: string;
    /**
     * Windows
     */
    windows: number;
    /**
     * Windows Read
     */
    windows_read: number;
    /**
     * Warnings
     */
    warnings: Array<string>;
    /**
     * Stores
     *
     * Product pages of catalogued stores.
     */
    stores: Array<StoreTabsOut>;
    /**
     * Uncatalogued
     *
     * Shopify-shaped product pages from stores without a recipe yet.
     */
    uncatalogued: Array<UncataloguedOut>;
    /**
     * Store Pages
     *
     * Other pages of catalogued stores (carts, collections).
     */
    store_pages: number;
    /**
     * Other
     *
     * Tabs that aren't stores.
     */
    other: number;
    /**
     * Dropped Local
     */
    dropped_local: number;
    /**
     * Duplicates
     */
    duplicates: number;
};

/**
 * OracleTagOut
 *
 * A Scryfall Tagger oracle tag (``id`` is the stable UUID).
 */
export type OracleTagOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Label
     */
    label: string;
};

/**
 * OverpayOut
 */
export type OverpayOut = {
    /**
     * Scryfall Id
     */
    scryfall_id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set
     */
    set: string;
    /**
     * Num
     */
    num: string;
    /**
     * Fin
     */
    fin: string;
    /**
     * Qty
     */
    qty: number;
    /**
     * Your
     */
    your: number | null;
    /**
     * Market
     */
    market: number | null;
    /**
     * Over
     */
    over?: number | null;
    /**
     * Pct
     */
    pct?: number | null;
};

/**
 * OwnedOut
 */
export type OwnedOut = {
    /**
     * Scryfall Id
     */
    scryfall_id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set
     */
    set: string;
    /**
     * Num
     */
    num: string;
    /**
     * Fin
     */
    fin: string;
    /**
     * Owned Qty
     */
    owned_qty: number;
    /**
     * Your
     */
    your: number;
};

/**
 * PairedOut
 */
export type PairedOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    facts: FactsOut;
    /**
     * Bucket
     */
    bucket: 'a_only' | 'both' | 'b_only';
    a: EntryOut | null;
    b: EntryOut | null;
    /**
     * Gap
     */
    gap: number | null;
};

/**
 * PieceOut
 */
export type PieceOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * In Deck
     *
     * The deck already runs this card (deck combos only).
     */
    in_deck: boolean;
    /**
     * Owned / free copies across printings, cheapest price, display printing.
     */
    facts: FactsOut;
    /**
     * Image Uri
     *
     * Spellbook's art crop, for cards not in the local catalog.
     */
    image_uri: string | null;
    /**
     * The printing to add: your copy with the most free, else the first standard printing.
     */
    printing?: PrintingOut | null;
};

/**
 * PreconOptionOut
 */
export type PreconOptionOut = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Type
     */
    type: string;
    /**
     * Release Date
     */
    release_date: string | null;
    /**
     * Default State
     */
    default_state: 'built' | 'deconstructed';
    /**
     * Owned Built
     */
    owned_built: number;
    /**
     * Owned Deconstructed
     */
    owned_deconstructed: number;
};

/**
 * PreviewOut
 */
export type PreviewOut = {
    /**
     * Built
     */
    built: boolean;
    /**
     * Changes
     */
    changes: Array<ChangeOut>;
    /**
     * Physical swap list; only for a built deck.
     */
    swap: SwapOut | null;
};

/**
 * PriceOut
 */
export type PriceOut = {
    /**
     * Url
     */
    url: string;
    /**
     * Vendor
     */
    vendor?: string | null;
    /**
     * Price
     */
    price: number | null;
    /**
     * Currency
     */
    currency: string | null;
    /**
     * Available
     *
     * None when the page doesn't say.
     */
    available: boolean | null;
    /**
     * Title
     */
    title: string | null;
    /**
     * Signal
     *
     * Which signal gave the price: shopify, meta, json-ld, microdata, pattern.
     */
    signal: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Kind
     */
    kind?: 'sealed' | 'sld' | 'single' | 'other_game' | 'unknown' | null;
    /**
     * Status
     */
    status?: 'matched' | 'ambiguous' | 'unmatched' | 'skipped' | 'confirmed' | null;
    match?: MatchOut | null;
    /**
     * Candidates
     */
    candidates?: Array<MatchOut>;
    /**
     * Note
     */
    note?: string;
    /**
     * Market
     *
     * Sealed market, Secret Lair market, or the single's price.
     */
    market?: number | null;
    /**
     * Contents
     *
     * What the cards inside are worth (sealed / Secret Lair).
     */
    contents?: number | null;
    /**
     * Partial
     *
     * Some cards inside have no price — contents undercounts.
     */
    partial?: boolean;
    /**
     * Delta
     *
     * Face price minus market (negative = below market).
     */
    delta?: number | null;
    /**
     * Pct
     */
    pct?: number | null;
    /**
     * Watching
     *
     * This link is on your watchlist (its price history is kept).
     */
    watching?: boolean;
};

/**
 * PricePointOut
 */
export type PricePointOut = {
    /**
     * Price
     */
    price: number | null;
    /**
     * At
     */
    at: string;
};

/**
 * PrintingOut
 *
 * One exact printing a line can resolve to (what the picker shows).
 */
export type PrintingOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Set Name
     */
    set_name: string | null;
    /**
     * Collector Number
     */
    collector_number: string;
    /**
     * Rarity
     */
    rarity: string;
    /**
     * Finishes
     *
     * Inventory finishes (etched counts as foil).
     */
    finishes: Array<'nonfoil' | 'foil'>;
    /**
     * Treatment
     *
     * treatments.compute_treatment code, '' for a standard frame.
     */
    treatment: string;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Price Usd
     */
    price_usd: number | null;
    /**
     * Price Usd Foil
     */
    price_usd_foil: number | null;
    /**
     * Released At
     */
    released_at: string | null;
    /**
     * Type Line
     */
    type_line?: string | null;
    /**
     * Cmc
     */
    cmc?: number | null;
    /**
     * Owned
     *
     * Copies you already own, per finish.
     */
    owned?: {
        [key: string]: number;
    };
    /**
     * Free
     *
     * Owned copies no built deck has pledged (all finishes).
     */
    free?: number;
};

/**
 * ProductCostOut
 */
export type ProductCostOut = {
    /**
     * Kind
     */
    kind: 'sealed' | 'sld';
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Finish
     */
    finish?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Subtype
     */
    subtype?: string | null;
    /**
     * Release Date
     */
    release_date?: string | null;
    /**
     * Market
     *
     * The sealed product's own market price.
     */
    market?: number | null;
    /**
     * Market Source
     */
    market_source?: string | null;
    /**
     * Contents
     *
     * What's inside: known cards (exact printings) + booster EV.
     */
    contents?: number | null;
    /**
     * Exact
     *
     * Known cards at their exact printings + booster EV.
     */
    exact?: number | null;
    /**
     * Floor
     *
     * Known cards at each card's cheapest printing + booster EV.
     */
    floor?: number | null;
    /**
     * Known Exact
     *
     * Known cards only, exact printings.
     */
    known_exact?: number | null;
    /**
     * Known Floor
     *
     * Known cards only, cheapest printings.
     */
    known_floor?: number | null;
    /**
     * Booster Ev
     *
     * Expected value of the random boosters inside.
     */
    booster_ev?: number | null;
    /**
     * Booster Only
     */
    booster_only?: boolean;
    /**
     * Total Cards
     */
    total_cards?: number;
    /**
     * Unpriced
     *
     * Known cards with no price at their exact printing.
     */
    unpriced?: number;
    /**
     * Notes
     */
    notes?: Array<string>;
    /**
     * Sealed Name
     *
     * Secret Lair: the MTGJSON sealed product valued (None for older drops without one).
     */
    sealed_name?: string | null;
    /**
     * Lines
     *
     * Every known card (exact + cheapest printing, your free copies).
     */
    lines?: Array<DeckLineOut>;
};

/**
 * ProductOut
 */
export type ProductOut = {
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Subtype
     */
    subtype?: string | null;
    /**
     * Release Date
     */
    release_date?: string | null;
    /**
     * Tcgplayer Url
     */
    tcgplayer_url?: string | null;
};

/**
 * ProductValueOut
 */
export type ProductValueOut = {
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Sealed Market
     *
     * The sealed product's own market price.
     */
    sealed_market?: number | null;
    /**
     * Market Source
     */
    market_source?: string | null;
    /**
     * Contents Value
     *
     * What's inside: fixed cards + booster EV.
     */
    contents_value?: number | null;
    /**
     * Exact Singles
     *
     * Σ the product's exact card printings.
     */
    exact_singles?: number | null;
    /**
     * Floor Singles
     *
     * Σ the cheapest printing of each card anywhere.
     */
    floor_singles?: number | null;
    /**
     * Booster Only
     */
    booster_only?: boolean;
    /**
     * Coverage
     */
    coverage?: number | null;
    /**
     * Unpriced Cards
     *
     * Fixed cards with no price at their exact printing (contents value undercounts).
     */
    unpriced_cards?: number;
    /**
     * Total Cards
     */
    total_cards?: number;
    /**
     * Notes
     */
    notes?: Array<string>;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * RankedOut
 */
export type RankedOut = {
    /**
     * Rank
     */
    rank: number | null;
    /**
     * Name
     */
    name: string;
    /**
     * Slug
     */
    slug: string;
    facts: FactsOut;
    /**
     * Num Decks
     */
    num_decks?: number | null;
    /**
     * Salt
     *
     * Average 0–4 'unfun to play against' rating (salt rankings).
     */
    salt?: number | null;
    /**
     * Trend
     *
     * EDHREC trend z-score.
     */
    trend?: number | null;
};

/**
 * RankingOptionsOut
 */
export type RankingOptionsOut = {
    /**
     * Timeframes
     */
    timeframes: Array<string>;
    /**
     * Colors
     */
    colors: Array<ColorOptionOut>;
    /**
     * Tags
     *
     * Tags already fetched (suggestions).
     */
    tags: Array<string>;
};

/**
 * RankingOut
 */
export type RankingOut = {
    /**
     * Scope
     */
    scope: 'commanders' | 'cards' | 'salt';
    /**
     * Timeframe
     *
     * Stored timeframe: week|month|year, 'all' (salt, tag) or '' (set).
     */
    timeframe: string;
    /**
     * Filter
     *
     * '' | color:<slug> | tag:<slug> | set:<anchor>.
     */
    filter: string;
    /**
     * Title
     */
    title: string;
    /**
     * Cached
     *
     * False = never fetched; run the edhrec.rankings job.
     */
    cached: boolean;
    /**
     * Fetched At
     */
    fetched_at: string | null;
    /**
     * Rows
     */
    rows: Array<RankedOut>;
};

/**
 * ResolveIn
 */
export type ResolveIn = {
    /**
     * Text
     */
    text: string;
    /**
     * Format
     */
    format?: 'auto' | 'moxfield' | 'tcgplayer' | 'names';
};

/**
 * ResolveOut
 */
export type ResolveOut = {
    /**
     * Format
     */
    format: 'moxfield' | 'tcgplayer' | 'names' | 'deck';
    /**
     * Lines
     */
    lines: Array<ResolvedLineOut>;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Deck Name
     */
    deck_name?: string | null;
    /**
     * Deck URL fetches only: the source deck, to save its decklist.
     */
    deck?: DeckSourceOut | null;
};

/**
 * ResolvedLineOut
 */
export type ResolvedLineOut = {
    /**
     * Line
     *
     * 1-based line number in the pasted text (0 for fetched decks).
     */
    line: number;
    /**
     * Raw
     */
    raw: string;
    /**
     * Qty
     */
    qty: number;
    /**
     * Name
     */
    name: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Section
     */
    section: string;
    /**
     * Status
     */
    status: 'exact' | 'ambiguous' | 'unresolved';
    /**
     * Candidates
     *
     * Exact: one. Ambiguous: every printing of the name, best guess first. Unresolved: empty.
     */
    candidates: Array<PrintingOut>;
    /**
     * Chosen
     *
     * scryfall_id of the default pick (None when unresolved).
     */
    chosen: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * SaveIn
 */
export type SaveIn = {
    /**
     * Cards
     */
    cards: Array<DraftCardIn>;
    /**
     * Expected Version Id
     */
    expected_version_id: number;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * SaveOut
 */
export type SaveOut = {
    /**
     * Built
     */
    built: boolean;
    /**
     * Changes
     */
    changes: Array<ChangeOut>;
    /**
     * Physical swap list; only for a built deck.
     */
    swap: SwapOut | null;
    /**
     * Version Number
     *
     * New version number; null when nothing changed.
     */
    version_number: number | null;
    /**
     * Pulled
     */
    pulled: number;
    /**
     * Sleeved
     */
    sleeved: number;
};

/**
 * SearchOut
 */
export type SearchOut = {
    /**
     * Query
     */
    query: string;
    /**
     * Source
     */
    source: 'local' | 'scryfall';
    /**
     * Printings
     */
    printings: Array<PrintingOut>;
};

/**
 * SetRefOut
 */
export type SetRefOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * SldDropOut
 */
export type SldDropOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Release Date
     */
    release_date?: string | null;
    /**
     * Editions
     */
    editions: Array<SldEditionOut>;
};

/**
 * SldDropsOut
 */
export type SldDropsOut = {
    /**
     * Total
     *
     * Every Secret Lair drop known.
     */
    total: number;
    /**
     * Drops
     *
     * The most recent drops, newest first. Values: GET /api/market/product-cost?kind=sld.
     */
    drops: Array<SldDropOut>;
};

/**
 * SldEditionOut
 */
export type SldEditionOut = {
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Sealed Name
     *
     * The MTGJSON sealed product for this edition, if listed.
     */
    sealed_name?: string | null;
    /**
     * Tcgplayer Url
     *
     * Its TCGplayer product page — the link a watched drop tracks.
     */
    tcgplayer_url?: string | null;
};

/**
 * SourceOut
 */
export type SourceOut = {
    /**
     * Key
     *
     * 'singles' | 'unknown' | 'product:<MTGJSON fileName>'
     */
    key: string;
    /**
     * Kind
     *
     * deck = playable precon; pool = card pool (land pack, scene box, most Secret Lair drops); singles = bought/added individually; unknown = provenance not reconstructed.
     */
    kind: 'singles' | 'unknown' | 'deck' | 'pool';
    /**
     * Label
     */
    label: string;
    /**
     * Set Code
     */
    set_code?: string | null;
    /**
     * Printings
     *
     * Owned printings in this view acquired from this source.
     */
    printings?: number;
};

/**
 * StoreTabsOut
 */
export type StoreTabsOut = {
    /**
     * Key
     */
    key: string;
    /**
     * Name
     */
    name: string;
    /**
     * Mode
     *
     * How prices are read: shopify/meta server-side, rendered from your open tab.
     */
    mode: 'shopify' | 'meta' | 'rendered';
    /**
     * No Sales Tax
     */
    no_sales_tax: boolean;
    /**
     * Tabs
     */
    tabs: Array<TabOut>;
};

/**
 * SuggestionOut
 */
export type SuggestionOut = {
    printing: PrintingOut;
    /**
     * Inclusion Pct
     */
    inclusion_pct: number | null;
    /**
     * Synergy
     */
    synergy: number | null;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Owned
     *
     * Copies owned across every printing of the card.
     */
    owned: number;
    /**
     * Free
     *
     * Owned copies no built deck has pledged, across printings.
     */
    free: number;
};

/**
 * SuggestionsOut
 */
export type SuggestionsOut = {
    /**
     * Commander
     */
    commander: string;
    /**
     * Cards
     */
    cards: Array<SuggestionOut>;
};

/**
 * SwapLineOut
 */
export type SwapLineOut = {
    printing: PrintingOut;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Qty
     */
    qty: number;
};

/**
 * SwapOut
 */
export type SwapOut = {
    /**
     * Pull
     *
     * Copies to take out of the built deck (they return to the free pool).
     */
    pull: Array<SwapLineOut>;
    /**
     * Sleeve
     *
     * Free copies to put into the built deck (pledged).
     */
    sleeve: Array<SwapLineOut>;
    /**
     * Short
     *
     * Copies the deck needs that you don't have free.
     */
    short: Array<SwapLineOut>;
};

/**
 * TabOut
 */
export type TabOut = {
    /**
     * Url
     */
    url: string;
    /**
     * Title
     */
    title: string;
    /**
     * Window
     */
    window: number;
    /**
     * Tab
     */
    tab: number;
};

/**
 * TreeNodeOut
 */
export type TreeNodeOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Count
     */
    count: number;
    /**
     * Market
     */
    market: number | null;
    /**
     * Contents Value
     */
    contents_value: number | null;
    /**
     * Contents Kind
     */
    contents_kind: string;
    /**
     * Children
     */
    children?: Array<TreeNodeOut>;
};

/**
 * UncataloguedOut
 */
export type UncataloguedOut = {
    /**
     * Host
     */
    host: string;
    /**
     * Tabs
     */
    tabs: Array<TabOut>;
};

/**
 * UndoOut
 */
export type UndoOut = {
    /**
     * Taken At
     *
     * UTC ISO time the restore point was taken.
     */
    taken_at: string;
    /**
     * Reason
     */
    reason: string;
    /**
     * Restorable
     *
     * False when the database changed shape since.
     */
    restorable: boolean;
    current: UndoSummary;
    snapshot: UndoSummary;
    /**
     * Snapshot minus current: what restoring would change.
     */
    changes: UndoSummary;
};

/**
 * UndoSummary
 */
export type UndoSummary = {
    /**
     * Copies
     */
    copies: number;
    /**
     * Printings
     */
    printings: number;
    /**
     * Decks
     */
    decks: number;
    /**
     * Built
     */
    built: number;
    /**
     * Wishlist
     */
    wishlist: number;
    /**
     * Earmarks
     */
    earmarks: number;
};

/**
 * UnidentifiedOut
 */
export type UnidentifiedOut = {
    /**
     * Name
     */
    name: string | null;
    /**
     * Set
     */
    set: string | null;
    /**
     * Num
     */
    num: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * ViolationOut
 */
export type ViolationOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Severity
     */
    severity: 'error' | 'warning' | 'info';
    /**
     * Message
     */
    message: string;
    /**
     * Cards
     */
    cards: Array<string>;
};

/**
 * WatchIn
 */
export type WatchIn = {
    /**
     * Url
     */
    url: string;
    choice: MatchOut;
    /**
     * Price
     */
    price?: number | null;
    /**
     * Currency
     */
    currency?: string | null;
};

/**
 * WatchOut
 */
export type WatchOut = {
    /**
     * Watching
     */
    watching: boolean;
    /**
     * Message
     */
    message: string;
};

/**
 * WatchStoreOut
 */
export type WatchStoreOut = {
    /**
     * Url
     */
    url: string;
    /**
     * Store
     */
    store: string | null;
    /**
     * Price
     */
    price: number | null;
    /**
     * Available
     */
    available: boolean | null;
    /**
     * Read At
     */
    read_at: string;
    /**
     * Read
     *
     * False when the latest price is still the earmark's saved asking price.
     */
    read: boolean;
    /**
     * First Price
     */
    first_price: number | null;
    /**
     * First At
     */
    first_at: string;
    /**
     * Change
     *
     * Latest minus first price seen here.
     */
    change: number | null;
    /**
     * History
     */
    history: Array<PricePointOut>;
};

/**
 * WatchedOut
 */
export type WatchedOut = {
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Kind
     */
    kind: 'sealed' | 'sld' | 'single';
    /**
     * Finish
     */
    finish?: string | null;
    /**
     * Scryfall Id
     *
     * Singles: the watched printing.
     */
    scryfall_id?: string | null;
    /**
     * Category
     */
    category: string | null;
    /**
     * Subtype
     */
    subtype?: string | null;
    /**
     * Release Date
     */
    release_date: string | null;
    /**
     * Market
     */
    market?: number | null;
    /**
     * Contents
     */
    contents?: number | null;
    /**
     * Partial
     */
    partial?: boolean;
    /**
     * Best Price
     */
    best_price: number | null;
    /**
     * Best Store
     */
    best_store: string | null;
    /**
     * Best Url
     */
    best_url: string | null;
    /**
     * Delta
     */
    delta?: number | null;
    /**
     * Pct
     */
    pct?: number | null;
    /**
     * Stores
     */
    stores: Array<WatchStoreOut>;
    /**
     * Error
     */
    error?: string | null;
};

export type JobSpecsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs/specs';
};

export type JobSpecsResponses = {
    /**
     * Response Job Specs
     *
     * Successful Response
     */
    200: Array<JobSpecOut>;
};

export type JobSpecsResponse = JobSpecsResponses[keyof JobSpecsResponses];

export type SubmitJobData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/jobs/{name}';
};

export type SubmitJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors];

export type SubmitJobResponses = {
    /**
     * Successful Response
     */
    202: JobOut;
};

export type SubmitJobResponse = SubmitJobResponses[keyof SubmitJobResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type ListJobsResponses = {
    /**
     * Response List Jobs
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type JobEventsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/events';
};

export type JobEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobEventsError = JobEventsErrors[keyof JobEventsErrors];

export type JobEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CommandersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/edhrec/commanders';
};

export type CommandersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommandersError = CommandersErrors[keyof CommandersErrors];

export type CommandersResponses = {
    /**
     * Response Commanders
     *
     * Successful Response
     */
    200: Array<CommanderOption>;
};

export type CommandersResponse = CommandersResponses[keyof CommandersResponses];

export type CompareData = {
    body?: never;
    path?: never;
    query: {
        /**
         * A
         */
        a: string;
        /**
         * B
         */
        b?: string | null;
    };
    url: '/api/edhrec/compare';
};

export type CompareErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareError = CompareErrors[keyof CompareErrors];

export type CompareResponses = {
    /**
     * Successful Response
     */
    200: CompareOut;
};

export type CompareResponse = CompareResponses[keyof CompareResponses];

export type ExploreSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/explore/search';
};

export type ExploreSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExploreSearchError = ExploreSearchErrors[keyof ExploreSearchErrors];

export type ExploreSearchResponses = {
    /**
     * Response Explore Search
     *
     * Successful Response
     */
    200: Array<CardOptionOut>;
};

export type ExploreSearchResponse = ExploreSearchResponses[keyof ExploreSearchResponses];

export type ExploreCardData = {
    body?: never;
    path?: never;
    query: {
        /**
         * A
         */
        a: string;
        /**
         * B
         */
        b?: string | null;
    };
    url: '/api/explore/card';
};

export type ExploreCardErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExploreCardError = ExploreCardErrors[keyof ExploreCardErrors];

export type ExploreCardResponses = {
    /**
     * Successful Response
     */
    200: CardExploreOut;
};

export type ExploreCardResponse = ExploreCardResponses[keyof ExploreCardResponses];

export type ExploreRankingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Scope
         */
        scope?: 'commanders' | 'cards' | 'salt';
        /**
         * Timeframe
         *
         * Ignored by salt, tag and set rankings.
         */
        timeframe?: 'week' | 'month' | 'year';
        /**
         * Color
         *
         * Color identity: WUBRG letters or an EDHREC name (azorius, mono-red…).
         */
        color?: string | null;
        /**
         * Tag
         *
         * Creature type or theme, e.g. goblins, treasure.
         */
        tag?: string | null;
        /**
         * Set Family
         *
         * Set family anchor or name, e.g. fin.
         */
        set_family?: string | null;
    };
    url: '/api/explore/ranking';
};

export type ExploreRankingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExploreRankingError = ExploreRankingErrors[keyof ExploreRankingErrors];

export type ExploreRankingResponses = {
    /**
     * Successful Response
     */
    200: RankingOut;
};

export type ExploreRankingResponse = ExploreRankingResponses[keyof ExploreRankingResponses];

export type ExploreRankingOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/explore/ranking/options';
};

export type ExploreRankingOptionsResponses = {
    /**
     * Successful Response
     */
    200: RankingOptionsOut;
};

export type ExploreRankingOptionsResponse = ExploreRankingOptionsResponses[keyof ExploreRankingOptionsResponses];

export type DealsTabsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Browser
         */
        browser?: 'chrome' | 'safari';
    };
    url: '/api/deals/tabs';
};

export type DealsTabsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DealsTabsError = DealsTabsErrors[keyof DealsTabsErrors];

export type DealsTabsResponses = {
    /**
     * Successful Response
     */
    200: OpenTabsOut;
};

export type DealsTabsResponse = DealsTabsResponses[keyof DealsTabsResponses];

export type DealsMatchData = {
    body: ConfirmIn;
    path?: never;
    query?: never;
    url: '/api/deals/match';
};

export type DealsMatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DealsMatchError = DealsMatchErrors[keyof DealsMatchErrors];

export type DealsMatchResponses = {
    /**
     * Successful Response
     */
    200: PriceOut;
};

export type DealsMatchResponse = DealsMatchResponses[keyof DealsMatchResponses];

export type DealsUnwatchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
    };
    url: '/api/deals/watch';
};

export type DealsUnwatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DealsUnwatchError = DealsUnwatchErrors[keyof DealsUnwatchErrors];

export type DealsUnwatchResponses = {
    /**
     * Successful Response
     */
    200: WatchOut;
};

export type DealsUnwatchResponse = DealsUnwatchResponses[keyof DealsUnwatchResponses];

export type DealsWatchData = {
    body: WatchIn;
    path?: never;
    query?: never;
    url: '/api/deals/watch';
};

export type DealsWatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DealsWatchError = DealsWatchErrors[keyof DealsWatchErrors];

export type DealsWatchResponses = {
    /**
     * Successful Response
     */
    200: WatchOut;
};

export type DealsWatchResponse = DealsWatchResponses[keyof DealsWatchResponses];

export type DealsWatchedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/deals/watched';
};

export type DealsWatchedResponses = {
    /**
     * Response Deals Watched
     *
     * Successful Response
     */
    200: Array<WatchedOut>;
};

export type DealsWatchedResponse = DealsWatchedResponses[keyof DealsWatchedResponses];

export type UndoInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/undo';
};

export type UndoInfoResponses = {
    /**
     * Response Undo Info
     *
     * Successful Response
     */
    200: UndoOut | null;
};

export type UndoInfoResponse = UndoInfoResponses[keyof UndoInfoResponses];

export type UndoRestoreData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/undo/restore';
};

export type UndoRestoreResponses = {
    /**
     * Successful Response
     */
    200: UndoOut;
};

export type UndoRestoreResponse = UndoRestoreResponses[keyof UndoRestoreResponses];

export type FeaturesRouteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/features';
};

export type FeaturesRouteResponses = {
    /**
     * Successful Response
     */
    200: FeaturesOut;
};

export type FeaturesRouteResponse = FeaturesRouteResponses[keyof FeaturesRouteResponses];

export type CartSetupData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cart/setup';
};

export type CartSetupResponses = {
    /**
     * Successful Response
     */
    200: CartSetupOut;
};

export type CartSetupResponse = CartSetupResponses[keyof CartSetupResponses];

export type CartCheckData = {
    body: CartIn;
    path?: never;
    query?: never;
    url: '/api/cart/check';
};

export type CartCheckErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CartCheckError = CartCheckErrors[keyof CartCheckErrors];

export type CartCheckResponses = {
    /**
     * Successful Response
     */
    200: CartAuditOut;
};

export type CartCheckResponse = CartCheckResponses[keyof CartCheckResponses];

export type MarketProductsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/api/market/products';
};

export type MarketProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketProductsError = MarketProductsErrors[keyof MarketProductsErrors];

export type MarketProductsResponses = {
    /**
     * Successful Response
     */
    200: FamilyProductsOut;
};

export type MarketProductsResponse = MarketProductsResponses[keyof MarketProductsResponses];

export type MarketValueData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Set
         */
        set: string;
        /**
         * Name
         */
        name: string;
    };
    url: '/api/market/value';
};

export type MarketValueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketValueError = MarketValueErrors[keyof MarketValueErrors];

export type MarketValueResponses = {
    /**
     * Successful Response
     */
    200: ProductValueOut;
};

export type MarketValueResponse = MarketValueResponses[keyof MarketValueResponses];

export type MarketProductTreeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Set
         */
        set: string;
        /**
         * Name
         */
        name: string;
    };
    url: '/api/market/product-tree';
};

export type MarketProductTreeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketProductTreeError = MarketProductTreeErrors[keyof MarketProductTreeErrors];

export type MarketProductTreeResponses = {
    /**
     * Successful Response
     */
    200: TreeNodeOut;
};

export type MarketProductTreeResponse = MarketProductTreeResponses[keyof MarketProductTreeResponses];

export type MarketProductCostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Kind
         */
        kind: 'sealed' | 'sld';
        /**
         * Set
         */
        set: string;
        /**
         * Name
         */
        name: string;
        /**
         * Finish
         */
        finish?: string | null;
    };
    url: '/api/market/product-cost';
};

export type MarketProductCostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketProductCostError = MarketProductCostErrors[keyof MarketProductCostErrors];

export type MarketProductCostResponses = {
    /**
     * Successful Response
     */
    200: ProductCostOut;
};

export type MarketProductCostResponse = MarketProductCostResponses[keyof MarketProductCostResponses];

export type MarketSecretLairData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/market/secret-lair';
};

export type MarketSecretLairErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketSecretLairError = MarketSecretLairErrors[keyof MarketSecretLairErrors];

export type MarketSecretLairResponses = {
    /**
     * Successful Response
     */
    200: SldDropsOut;
};

export type MarketSecretLairResponse = MarketSecretLairResponses[keyof MarketSecretLairResponses];

export type MarketCardsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         */
        code: string;
    };
    url: '/api/market/cards';
};

export type MarketCardsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketCardsError = MarketCardsErrors[keyof MarketCardsErrors];

export type MarketCardsResponses = {
    /**
     * Successful Response
     */
    200: FamilyCardsOut;
};

export type MarketCardsResponse = MarketCardsResponses[keyof MarketCardsResponses];

export type MarketDeckData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Slug
         */
        slug: string;
    };
    url: '/api/market/deck';
};

export type MarketDeckErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarketDeckError = MarketDeckErrors[keyof MarketDeckErrors];

export type MarketDeckResponses = {
    /**
     * Successful Response
     */
    200: DeckCostOut;
};

export type MarketDeckResponse = MarketDeckResponses[keyof MarketDeckResponses];

export type CollectionFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/collection/families';
};

export type CollectionFamiliesResponses = {
    /**
     * Response Collection Families
     *
     * Successful Response
     */
    200: Array<FamilyOption>;
};

export type CollectionFamiliesResponse = CollectionFamiliesResponses[keyof CollectionFamiliesResponses];

export type CollectionData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Families
         */
        families: Array<string>;
    };
    url: '/api/collection';
};

export type CollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionError = CollectionErrors[keyof CollectionErrors];

export type CollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionOut;
};

export type CollectionResponse = CollectionResponses[keyof CollectionResponses];

export type CollectionBuyListData = {
    body: BuyListIn;
    path?: never;
    query?: never;
    url: '/api/collection/buy-list';
};

export type CollectionBuyListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionBuyListError = CollectionBuyListErrors[keyof CollectionBuyListErrors];

export type CollectionBuyListResponses = {
    /**
     * Successful Response
     */
    200: BuyListOut;
};

export type CollectionBuyListResponse = CollectionBuyListResponses[keyof CollectionBuyListResponses];

export type CollectionChecklistData = {
    body: ChecklistIn;
    path?: never;
    query?: never;
    url: '/api/collection/checklist';
};

export type CollectionChecklistErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionChecklistError = CollectionChecklistErrors[keyof CollectionChecklistErrors];

export type CollectionChecklistResponses = {
    /**
     * Successful Response
     */
    200: ChecklistOut;
};

export type CollectionChecklistResponse = CollectionChecklistResponses[keyof CollectionChecklistResponses];

export type DeckListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/decks';
};

export type DeckListResponses = {
    /**
     * Response Deck List
     *
     * Successful Response
     */
    200: Array<DeckSummaryOut>;
};

export type DeckListResponse = DeckListResponses[keyof DeckListResponses];

export type DeckCreateData = {
    body: NewDeckIn;
    path?: never;
    query?: never;
    url: '/api/decks';
};

export type DeckCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckCreateError = DeckCreateErrors[keyof DeckCreateErrors];

export type DeckCreateResponses = {
    /**
     * Successful Response
     */
    201: ActionOut;
};

export type DeckCreateResponse = DeckCreateResponses[keyof DeckCreateResponses];

export type DeckDetailData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}';
};

export type DeckDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckDetailError = DeckDetailErrors[keyof DeckDetailErrors];

export type DeckDetailResponses = {
    /**
     * Successful Response
     */
    200: DeckDetailOut;
};

export type DeckDetailResponse = DeckDetailResponses[keyof DeckDetailResponses];

export type DeckSaveData = {
    body: SaveIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}';
};

export type DeckSaveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckSaveError = DeckSaveErrors[keyof DeckSaveErrors];

export type DeckSaveResponses = {
    /**
     * Successful Response
     */
    200: SaveOut;
};

export type DeckSaveResponse = DeckSaveResponses[keyof DeckSaveResponses];

export type DeckImportData = {
    body: ImportIn;
    path?: never;
    query?: never;
    url: '/api/decks/import';
};

export type DeckImportErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckImportError = DeckImportErrors[keyof DeckImportErrors];

export type DeckImportResponses = {
    /**
     * Successful Response
     */
    200: ImportOut;
};

export type DeckImportResponse = DeckImportResponses[keyof DeckImportResponses];

export type DeckBuildPlanData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/build-plan';
};

export type DeckBuildPlanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckBuildPlanError = DeckBuildPlanErrors[keyof DeckBuildPlanErrors];

export type DeckBuildPlanResponses = {
    /**
     * Successful Response
     */
    200: BuildPlanOut;
};

export type DeckBuildPlanResponse = DeckBuildPlanResponses[keyof DeckBuildPlanResponses];

export type DeckBuildData = {
    body: BuildIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/build';
};

export type DeckBuildErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckBuildError = DeckBuildErrors[keyof DeckBuildErrors];

export type DeckBuildResponses = {
    /**
     * Successful Response
     */
    200: ActionOut;
};

export type DeckBuildResponse = DeckBuildResponses[keyof DeckBuildResponses];

export type DeckBreakDownData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/break-down';
};

export type DeckBreakDownErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckBreakDownError = DeckBreakDownErrors[keyof DeckBreakDownErrors];

export type DeckBreakDownResponses = {
    /**
     * Successful Response
     */
    200: ActionOut;
};

export type DeckBreakDownResponse = DeckBreakDownResponses[keyof DeckBreakDownResponses];

export type DeckCopyData = {
    body: CopyIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/copy';
};

export type DeckCopyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckCopyError = DeckCopyErrors[keyof DeckCopyErrors];

export type DeckCopyResponses = {
    /**
     * Successful Response
     */
    201: ActionOut;
};

export type DeckCopyResponse = DeckCopyResponses[keyof DeckCopyResponses];

export type DeckPreviewData = {
    body: DraftIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/preview';
};

export type DeckPreviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckPreviewError = DeckPreviewErrors[keyof DeckPreviewErrors];

export type DeckPreviewResponses = {
    /**
     * Successful Response
     */
    200: PreviewOut;
};

export type DeckPreviewResponse = DeckPreviewResponses[keyof DeckPreviewResponses];

export type DeckCheckData = {
    body: CheckIn;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/check';
};

export type DeckCheckErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckCheckError = DeckCheckErrors[keyof DeckCheckErrors];

export type DeckCheckResponses = {
    /**
     * Successful Response
     */
    200: CheckOut;
};

export type DeckCheckResponse = DeckCheckResponses[keyof DeckCheckResponses];

export type DeckSuggestionsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Commander
         */
        commander: string;
    };
    url: '/api/decks-suggestions';
};

export type DeckSuggestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckSuggestionsError = DeckSuggestionsErrors[keyof DeckSuggestionsErrors];

export type DeckSuggestionsResponses = {
    /**
     * Successful Response
     */
    200: SuggestionsOut;
};

export type DeckSuggestionsResponse = DeckSuggestionsResponses[keyof DeckSuggestionsResponses];

export type DeckCombosData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}/combos';
};

export type DeckCombosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckCombosError = DeckCombosErrors[keyof DeckCombosErrors];

export type DeckCombosResponses = {
    /**
     * Successful Response
     */
    200: DeckCombosOut;
};

export type DeckCombosResponse = DeckCombosResponses[keyof DeckCombosResponses];

export type DraftCombosData = {
    body: DraftCombosIn;
    path?: never;
    query?: never;
    url: '/api/combos/draft';
};

export type DraftCombosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DraftCombosError = DraftCombosErrors[keyof DraftCombosErrors];

export type DraftCombosResponses = {
    /**
     * Successful Response
     */
    200: DeckCombosOut;
};

export type DraftCombosResponse = DraftCombosResponses[keyof DraftCombosResponses];

export type CardCombosData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Name
         */
        name: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/combos/card';
};

export type CardCombosErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CardCombosError = CardCombosErrors[keyof CardCombosErrors];

export type CardCombosResponses = {
    /**
     * Successful Response
     */
    200: CardCombosOut;
};

export type CardCombosResponse = CardCombosResponses[keyof CardCombosResponses];

export type CardHoldingsData = {
    body?: never;
    path: {
        /**
         * Scryfall Id
         */
        scryfall_id: string;
    };
    query?: never;
    url: '/api/cards/{scryfall_id}/holdings';
};

export type CardHoldingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CardHoldingsError = CardHoldingsErrors[keyof CardHoldingsErrors];

export type CardHoldingsResponses = {
    /**
     * Successful Response
     */
    200: HoldingsOut;
};

export type CardHoldingsResponse = CardHoldingsResponses[keyof CardHoldingsResponses];

export type HistoryListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/history';
};

export type HistoryListResponses = {
    /**
     * Successful Response
     */
    200: HistoryOut;
};

export type HistoryListResponse = HistoryListResponses[keyof HistoryListResponses];

export type HistoryEventData = {
    body?: never;
    path: {
        /**
         * Ingest Id
         */
        ingest_id: number;
    };
    query?: never;
    url: '/api/history/{ingest_id}';
};

export type HistoryEventErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HistoryEventError = HistoryEventErrors[keyof HistoryEventErrors];

export type HistoryEventResponses = {
    /**
     * Successful Response
     */
    200: HistoryEventOut;
};

export type HistoryEventResponse = HistoryEventResponses[keyof HistoryEventResponses];

export type IngestSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/ingest/search';
};

export type IngestSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestSearchError = IngestSearchErrors[keyof IngestSearchErrors];

export type IngestSearchResponses = {
    /**
     * Successful Response
     */
    200: SearchOut;
};

export type IngestSearchResponse = IngestSearchResponses[keyof IngestSearchResponses];

export type IngestResolveData = {
    body: ResolveIn;
    path?: never;
    query?: never;
    url: '/api/ingest/resolve';
};

export type IngestResolveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestResolveError = IngestResolveErrors[keyof IngestResolveErrors];

export type IngestResolveResponses = {
    /**
     * Successful Response
     */
    200: ResolveOut;
};

export type IngestResolveResponse = IngestResolveResponses[keyof IngestResolveResponses];

export type IngestCommitData = {
    body: CommitIn;
    path?: never;
    query?: never;
    url: '/api/ingest/commit';
};

export type IngestCommitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestCommitError = IngestCommitErrors[keyof IngestCommitErrors];

export type IngestCommitResponses = {
    /**
     * Successful Response
     */
    200: CommitOut;
};

export type IngestCommitResponse = IngestCommitResponses[keyof IngestCommitResponses];

export type IngestPreconsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/ingest/precons';
};

export type IngestPreconsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestPreconsError = IngestPreconsErrors[keyof IngestPreconsErrors];

export type IngestPreconsResponses = {
    /**
     * Response Ingest Precons
     *
     * Successful Response
     */
    200: Array<PreconOptionOut>;
};

export type IngestPreconsResponse = IngestPreconsResponses[keyof IngestPreconsResponses];
