// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CardDiffOut
 */
export type CardDiffOut = {
    /**
     * Families
     */
    families: Array<FamilyOut>;
    /**
     * Cards
     */
    cards: Array<CardDiffTile>;
    /**
     * Skipped
     *
     * Codes that didn't resolve to a configured family.
     */
    skipped?: Array<string>;
};

/**
 * CardDiffTile
 */
export type CardDiffTile = {
    /**
     * Key
     *
     * Stable per-family tile id (exact printing).
     */
    key: string;
    /**
     * Family
     */
    family: string;
    /**
     * Pools
     */
    pools: Array<'printing' | 'functional' | 'variant-chase'>;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string | null;
    /**
     * Collector Number
     */
    collector_number: string | null;
    /**
     * Rarity
     */
    rarity: string | null;
    /**
     * Finish
     */
    finish: string | null;
    /**
     * Usd
     */
    usd: number | null;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url: string | null;
    /**
     * Manapool Line
     */
    manapool_line?: string;
    /**
     * Tcgplayer Line
     */
    tcgplayer_line?: string;
};

/**
 * CommanderOption
 */
export type CommanderOption = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Cached
     *
     * EDHREC commander page already in the local cache.
     */
    cached: boolean;
};

/**
 * CompareCardOut
 */
export type CompareCardOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * A Pct
     */
    a_pct: number | null;
    /**
     * B Pct
     */
    b_pct: number | null;
    /**
     * A Decks
     */
    a_decks: number | null;
    /**
     * B Decks
     */
    b_decks: number | null;
    /**
     * Delta
     */
    delta: number | null;
    /**
     * Synergy A
     */
    synergy_a: number | null;
    /**
     * Synergy B
     */
    synergy_b: number | null;
    /**
     * Trend A
     */
    trend_a: number | null;
    /**
     * Trend B
     */
    trend_b: number | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Mana Cost
     */
    mana_cost: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string> | null;
    /**
     * Rarity
     */
    rarity: string | null;
    /**
     * Lowest Usd
     */
    lowest_usd: number | null;
    /**
     * Lowest Usd Foil
     */
    lowest_usd_foil: number | null;
    /**
     * Scryfall Id
     */
    scryfall_id: string | null;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Set Code
     */
    set_code: string | null;
    /**
     * Collector Number
     */
    collector_number: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url: string | null;
};

/**
 * CompareOut
 */
export type CompareOut = {
    /**
     * Name A
     */
    name_a: string;
    /**
     * Name B
     */
    name_b: string;
    /**
     * Slug A
     */
    slug_a: string;
    /**
     * Slug B
     */
    slug_b: string;
    /**
     * Cards
     */
    cards: Array<CompareCardOut>;
};

/**
 * FamilyOption
 */
export type FamilyOption = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * FamilyOut
 */
export type FamilyOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Owned Prints
     */
    owned_prints: number;
    /**
     * Owned Qty
     */
    owned_qty: number;
    /**
     * Owned Usd
     */
    owned_usd: number;
    /**
     * Pools
     */
    pools: {
        [key: string]: PoolSummary;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobOut
 */
export type JobOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Inputs
     */
    inputs: {
        [key: string]: unknown;
    };
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Progress
     */
    progress: {
        [key: string]: unknown;
    } | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Artifacts
     */
    artifacts: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Error
     */
    error: string | null;
};

/**
 * JobSpecOut
 */
export type JobSpecOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Mutates
     */
    mutates: boolean;
    /**
     * Input Schema
     */
    input_schema: {
        [key: string]: unknown;
    };
};

/**
 * PoolSummary
 */
export type PoolSummary = {
    /**
     * Count
     */
    count: number;
    /**
     * Usd
     */
    usd: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type JobSpecsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs/specs';
};

export type JobSpecsResponses = {
    /**
     * Response Job Specs
     *
     * Successful Response
     */
    200: Array<JobSpecOut>;
};

export type JobSpecsResponse = JobSpecsResponses[keyof JobSpecsResponses];

export type SubmitJobData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/jobs/{name}';
};

export type SubmitJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors];

export type SubmitJobResponses = {
    /**
     * Successful Response
     */
    202: JobOut;
};

export type SubmitJobResponse = SubmitJobResponses[keyof SubmitJobResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type ListJobsResponses = {
    /**
     * Response List Jobs
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type JobEventsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/events';
};

export type JobEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobEventsError = JobEventsErrors[keyof JobEventsErrors];

export type JobEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CommandersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/edhrec/commanders';
};

export type CommandersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommandersError = CommandersErrors[keyof CommandersErrors];

export type CommandersResponses = {
    /**
     * Response Commanders
     *
     * Successful Response
     */
    200: Array<CommanderOption>;
};

export type CommandersResponse = CommandersResponses[keyof CommandersResponses];

export type CompareData = {
    body?: never;
    path?: never;
    query: {
        /**
         * A
         */
        a: string;
        /**
         * B
         */
        b: string;
    };
    url: '/api/edhrec/compare';
};

export type CompareErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareError = CompareErrors[keyof CompareErrors];

export type CompareResponses = {
    /**
     * Successful Response
     */
    200: CompareOut;
};

export type CompareResponse = CompareResponses[keyof CompareResponses];

export type CardDiffFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/card-diff/families';
};

export type CardDiffFamiliesResponses = {
    /**
     * Response Card Diff Families
     *
     * Successful Response
     */
    200: Array<FamilyOption>;
};

export type CardDiffFamiliesResponse = CardDiffFamiliesResponses[keyof CardDiffFamiliesResponses];

export type CardDiffData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Families
         */
        families: Array<string>;
        /**
         * Pools
         */
        pools?: Array<'printing' | 'functional' | 'variant-chase'> | null;
        /**
         * Chase
         */
        chase?: 'exclude' | 'include' | 'only';
    };
    url: '/api/card-diff';
};

export type CardDiffErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CardDiffError = CardDiffErrors[keyof CardDiffErrors];

export type CardDiffResponses = {
    /**
     * Successful Response
     */
    200: CardDiffOut;
};

export type CardDiffResponse = CardDiffResponses[keyof CardDiffResponses];
