// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BuyItem
 */
export type BuyItem = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Qty
     */
    qty?: number;
};

/**
 * BuyListIn
 */
export type BuyListIn = {
    /**
     * Target
     */
    target: 'manapool' | 'tcgplayer' | 'cardkingdom' | 'moxfield' | 'plain';
    /**
     * Items
     */
    items: Array<BuyItem>;
};

/**
 * BuyListOut
 */
export type BuyListOut = {
    /**
     * Text
     */
    text: string;
    /**
     * Lines
     */
    lines: number;
};

/**
 * CardSourceOut
 */
export type CardSourceOut = {
    source: SourceOut;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Copies
     *
     * Copies acquired from this source (history: may exceed what is owned today).
     */
    copies: number;
};

/**
 * CollectionCardOut
 */
export type CollectionCardOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Family
     */
    family: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Collector Number
     */
    collector_number: string;
    /**
     * Rarity
     */
    rarity: string;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Released At
     */
    released_at: string | null;
    /**
     * Finishes
     */
    finishes: Array<string>;
    /**
     * Owned
     *
     * finish -> owned copies
     */
    owned: {
        [key: string]: number;
    };
    /**
     * Pledged
     *
     * finish -> copies pledged to built decks
     */
    pledged: {
        [key: string]: number;
    };
    /**
     * Price Usd
     */
    price_usd: number | null;
    /**
     * Price Usd Foil
     */
    price_usd_foil: number | null;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url: string | null;
    /**
     * Treatment
     *
     * Treatment codes (b, fa, shw, ext, sm, ff; '|'-joined); '' = plain
     */
    treatment: string;
    /**
     * Standard Frame
     */
    standard_frame: boolean;
    /**
     * Is Bulk
     */
    is_bulk: boolean;
    /**
     * Is Chase
     */
    is_chase: boolean;
    /**
     * Functions
     *
     * Function root keys (Scryfall Tagger roll-up).
     */
    functions?: Array<string>;
    /**
     * Sources
     *
     * Source keys this owned printing's copies were acquired from (see CollectionOut.sources).
     */
    sources?: Array<string>;
};

/**
 * CollectionOut
 */
export type CollectionOut = {
    /**
     * Families
     */
    families: Array<FamilySummaryOut>;
    /**
     * Cards
     */
    cards: Array<CollectionCardOut>;
    /**
     * Skipped
     *
     * Codes that didn't resolve to a family.
     */
    skipped?: Array<string>;
    /**
     * Functions
     *
     * Function roots, display order.
     */
    functions?: Array<FunctionRootOut>;
    /**
     * Sources
     *
     * Every source behind an owned printing in this view, most printings first.
     */
    sources?: Array<SourceOut>;
};

/**
 * CommanderOption
 */
export type CommanderOption = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Cached
     *
     * EDHREC commander page already in the local cache.
     */
    cached: boolean;
};

/**
 * CommitIn
 */
export type CommitIn = {
    /**
     * Items
     */
    items: Array<CommitItem>;
    /**
     * Source
     */
    source: 'search' | 'paste' | 'deck';
    /**
     * Label
     *
     * Free text recorded on the ingest event (e.g. a deck name).
     */
    label?: string | null;
};

/**
 * CommitItem
 */
export type CommitItem = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Qty
     */
    qty: number;
};

/**
 * CommitOut
 */
export type CommitOut = {
    /**
     * Ingest Id
     */
    ingest_id: number;
    /**
     * Copies
     */
    copies: number;
    /**
     * Printings
     */
    printings: number;
    /**
     * Summary
     */
    summary: string;
};

/**
 * CompareCardOut
 */
export type CompareCardOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Slug
     */
    slug: string;
    /**
     * Bucket
     */
    bucket: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * A Pct
     */
    a_pct: number | null;
    /**
     * B Pct
     */
    b_pct: number | null;
    /**
     * A Decks
     */
    a_decks: number | null;
    /**
     * B Decks
     */
    b_decks: number | null;
    /**
     * Delta
     */
    delta: number | null;
    /**
     * Synergy A
     */
    synergy_a: number | null;
    /**
     * Synergy B
     */
    synergy_b: number | null;
    /**
     * Trend A
     */
    trend_a: number | null;
    /**
     * Trend B
     */
    trend_b: number | null;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Mana Cost
     */
    mana_cost: string | null;
    /**
     * Color Identity
     */
    color_identity: Array<string> | null;
    /**
     * Rarity
     */
    rarity: string | null;
    /**
     * Lowest Usd
     */
    lowest_usd: number | null;
    /**
     * Lowest Usd Foil
     */
    lowest_usd_foil: number | null;
    /**
     * Scryfall Id
     */
    scryfall_id: string | null;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Set Code
     */
    set_code: string | null;
    /**
     * Collector Number
     */
    collector_number: string | null;
    /**
     * Scryfall Url
     */
    scryfall_url: string | null;
    /**
     * Functions
     *
     * Function root keys (Scryfall Tagger roll-up).
     */
    functions?: Array<string>;
    /**
     * Oracle Tags
     *
     * Top Tagger oracle tags by weight.
     */
    oracle_tags?: Array<OracleTagOut>;
};

/**
 * CompareOut
 */
export type CompareOut = {
    /**
     * Name A
     */
    name_a: string;
    /**
     * Name B
     */
    name_b: string;
    /**
     * Slug A
     */
    slug_a: string;
    /**
     * Slug B
     */
    slug_b: string;
    /**
     * Cards
     */
    cards: Array<CompareCardOut>;
    /**
     * Functions
     *
     * Function roots, display order.
     */
    functions?: Array<FunctionRootOut>;
};

/**
 * DeckCardOut
 */
export type DeckCardOut = {
    printing: PrintingOut;
    /**
     * Board
     */
    board: 'main' | 'side' | 'commander' | 'companion' | 'maybe' | 'token';
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil' | 'either';
    /**
     * Count
     */
    count: number;
    /**
     * Type Line
     */
    type_line: string | null;
    /**
     * Cmc
     */
    cmc: number | null;
    /**
     * Color Identity
     */
    color_identity: Array<string>;
    /**
     * Pledged Here
     *
     * Copies of this printing pledged to THIS deck (any finish).
     */
    pledged_here: number;
    /**
     * Free
     *
     * Copies you own that no deck has pledged (any finish).
     */
    free: number;
};

/**
 * DeckDetailOut
 */
export type DeckDetailOut = {
    deck: DeckSummaryOut;
    /**
     * Cards
     */
    cards: Array<DeckCardOut>;
};

/**
 * DeckPledgeOut
 */
export type DeckPledgeOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Count
     */
    count: number;
};

/**
 * DeckSummaryOut
 */
export type DeckSummaryOut = {
    /**
     * Slug
     */
    slug: string;
    /**
     * Name
     */
    name: string;
    /**
     * Format
     */
    format: string | null;
    /**
     * Deck Type
     *
     * What kind of deck: the game format (Commander, Standard, Pauper, Jumpstart…), else the precon product family (Starter / intro, Secret Lair, Land pack…).
     */
    deck_type: string;
    /**
     * State
     *
     * 'built' when at least one copy is built, else 'deconstructed'.
     */
    state: 'built' | 'deconstructed';
    /**
     * Built
     *
     * Copies of this recipe kept assembled (cards pledged).
     */
    built: number;
    /**
     * Loose
     *
     * Copies tracked as loose (recipe kept, cards in the collection).
     */
    loose: number;
    /**
     * Slugs
     *
     * Every deck row that is a copy of this recipe; `slug` is the representative (a built copy first).
     */
    slugs: Array<string>;
    /**
     * Origin
     *
     * precon = MTGJSON product; import = deck-builder URL; custom = hand-built.
     */
    origin: 'precon' | 'import' | 'custom';
    /**
     * Source
     *
     * Deck builder for imports (moxfield, archidekt…); precon product type for precons.
     */
    source: string | null;
    /**
     * Author
     */
    author: string | null;
    /**
     * Set Code
     */
    set_code: string | null;
    /**
     * Set Name
     */
    set_name: string | null;
    /**
     * Released
     *
     * Product release date (precons) or set release date; ISO.
     */
    released: string | null;
    /**
     * Cards
     *
     * Card count excluding tokens.
     */
    cards: number;
    /**
     * Value Usd
     *
     * Sum of non-token cards at their finish's price.
     */
    value_usd: number;
    /**
     * Pledged Pct
     *
     * Share of non-token card copies currently pledged to this deck (0–100).
     */
    pledged_pct: number;
    /**
     * Image Uri
     *
     * Representative art: the commander, else the priciest card.
     */
    image_uri: string | null;
};

/**
 * FamilyOption
 */
export type FamilyOption = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * FamilySummaryOut
 */
export type FamilySummaryOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
    /**
     * Printings
     */
    printings: number;
    /**
     * Owned Printings
     */
    owned_printings: number;
    /**
     * Owned Copies
     */
    owned_copies: number;
    /**
     * Owned Usd
     */
    owned_usd: number;
    /**
     * Missing Printings
     */
    missing_printings: number;
    /**
     * Missing Usd
     */
    missing_usd: number;
    /**
     * Sets
     *
     * Member sets with printings, oldest first.
     */
    sets?: Array<SetRefOut>;
};

/**
 * FunctionRootOut
 *
 * A curated function root (``config/function_tags.toml``), in display order.
 */
export type FunctionRootOut = {
    /**
     * Key
     */
    key: string;
    /**
     * Label
     */
    label: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HoldingsOut
 */
export type HoldingsOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Owned
     *
     * finish -> owned copies
     */
    owned: {
        [key: string]: number;
    };
    /**
     * Pledged
     *
     * finish -> copies pledged to built decks
     */
    pledged: {
        [key: string]: number;
    };
    /**
     * Free
     *
     * finish -> owned copies no deck has pledged
     */
    free: {
        [key: string]: number;
    };
    /**
     * Decks
     */
    decks: Array<DeckPledgeOut>;
    /**
     * Sources
     */
    sources: Array<CardSourceOut>;
    /**
     * Other Printings Owned
     *
     * Copies of the same card owned in other printings (all finishes).
     */
    other_printings_owned: number;
};

/**
 * JobOut
 */
export type JobOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Inputs
     */
    inputs: {
        [key: string]: unknown;
    };
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Progress
     */
    progress: {
        [key: string]: unknown;
    } | null;
    /**
     * Summary
     */
    summary: string | null;
    /**
     * Artifacts
     */
    artifacts: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Error
     */
    error: string | null;
};

/**
 * JobSpecOut
 */
export type JobSpecOut = {
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Mutates
     */
    mutates: boolean;
    /**
     * Input Schema
     */
    input_schema: {
        [key: string]: unknown;
    };
};

/**
 * OracleTagOut
 *
 * A Scryfall Tagger oracle tag (``id`` is the stable UUID).
 */
export type OracleTagOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    /**
     * Label
     */
    label: string;
};

/**
 * PreconOptionOut
 */
export type PreconOptionOut = {
    /**
     * File Name
     */
    file_name: string;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Type
     */
    type: string;
    /**
     * Release Date
     */
    release_date: string | null;
    /**
     * Default State
     */
    default_state: 'built' | 'deconstructed';
    /**
     * Owned Built
     */
    owned_built: number;
    /**
     * Owned Deconstructed
     */
    owned_deconstructed: number;
};

/**
 * PrintingOut
 *
 * One exact printing a line can resolve to (what the picker shows).
 */
export type PrintingOut = {
    /**
     * Scryfall Id
     */
    scryfall_id: string;
    /**
     * Oracle Id
     */
    oracle_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Set Code
     */
    set_code: string;
    /**
     * Set Name
     */
    set_name: string | null;
    /**
     * Collector Number
     */
    collector_number: string;
    /**
     * Rarity
     */
    rarity: string;
    /**
     * Finishes
     *
     * Inventory finishes (etched counts as foil).
     */
    finishes: Array<'nonfoil' | 'foil'>;
    /**
     * Treatment
     *
     * treatments.compute_treatment code, '' for a standard frame.
     */
    treatment: string;
    /**
     * Image Uri
     */
    image_uri: string | null;
    /**
     * Price Usd
     */
    price_usd: number | null;
    /**
     * Price Usd Foil
     */
    price_usd_foil: number | null;
    /**
     * Released At
     */
    released_at: string | null;
    /**
     * Owned
     *
     * Copies you already own, per finish.
     */
    owned?: {
        [key: string]: number;
    };
};

/**
 * ResolveIn
 */
export type ResolveIn = {
    /**
     * Text
     */
    text: string;
    /**
     * Format
     */
    format?: 'auto' | 'moxfield' | 'tcgplayer' | 'names';
};

/**
 * ResolveOut
 */
export type ResolveOut = {
    /**
     * Format
     */
    format: 'moxfield' | 'tcgplayer' | 'names' | 'deck';
    /**
     * Lines
     */
    lines: Array<ResolvedLineOut>;
    /**
     * Warnings
     */
    warnings?: Array<string>;
    /**
     * Deck Name
     */
    deck_name?: string | null;
};

/**
 * ResolvedLineOut
 */
export type ResolvedLineOut = {
    /**
     * Line
     *
     * 1-based line number in the pasted text (0 for fetched decks).
     */
    line: number;
    /**
     * Raw
     */
    raw: string;
    /**
     * Qty
     */
    qty: number;
    /**
     * Name
     */
    name: string;
    /**
     * Finish
     */
    finish: 'nonfoil' | 'foil';
    /**
     * Section
     */
    section: string;
    /**
     * Status
     */
    status: 'exact' | 'ambiguous' | 'unresolved';
    /**
     * Candidates
     *
     * Exact: one. Ambiguous: every printing of the name, best guess first. Unresolved: empty.
     */
    candidates: Array<PrintingOut>;
    /**
     * Chosen
     *
     * scryfall_id of the default pick (None when unresolved).
     */
    chosen: string | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * SearchOut
 */
export type SearchOut = {
    /**
     * Query
     */
    query: string;
    /**
     * Source
     */
    source: 'local' | 'scryfall';
    /**
     * Printings
     */
    printings: Array<PrintingOut>;
};

/**
 * SetRefOut
 */
export type SetRefOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Name
     */
    name: string;
};

/**
 * SourceOut
 */
export type SourceOut = {
    /**
     * Key
     *
     * 'singles' | 'unknown' | 'product:<MTGJSON fileName>'
     */
    key: string;
    /**
     * Kind
     *
     * deck = playable precon; pool = card pool (land pack, scene box, most Secret Lair drops); singles = bought/added individually; unknown = provenance not reconstructed.
     */
    kind: 'singles' | 'unknown' | 'deck' | 'pool';
    /**
     * Label
     */
    label: string;
    /**
     * Set Code
     */
    set_code?: string | null;
    /**
     * Printings
     *
     * Owned printings in this view acquired from this source.
     */
    printings?: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type JobSpecsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs/specs';
};

export type JobSpecsResponses = {
    /**
     * Response Job Specs
     *
     * Successful Response
     */
    200: Array<JobSpecOut>;
};

export type JobSpecsResponse = JobSpecsResponses[keyof JobSpecsResponses];

export type SubmitJobData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/api/jobs/{name}';
};

export type SubmitJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitJobError = SubmitJobErrors[keyof SubmitJobErrors];

export type SubmitJobResponses = {
    /**
     * Successful Response
     */
    202: JobOut;
};

export type SubmitJobResponse = SubmitJobResponses[keyof SubmitJobResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/jobs';
};

export type ListJobsResponses = {
    /**
     * Response List Jobs
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type JobEventsData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/events';
};

export type JobEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type JobEventsError = JobEventsErrors[keyof JobEventsErrors];

export type JobEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CommandersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/edhrec/commanders';
};

export type CommandersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CommandersError = CommandersErrors[keyof CommandersErrors];

export type CommandersResponses = {
    /**
     * Response Commanders
     *
     * Successful Response
     */
    200: Array<CommanderOption>;
};

export type CommandersResponse = CommandersResponses[keyof CommandersResponses];

export type CompareData = {
    body?: never;
    path?: never;
    query: {
        /**
         * A
         */
        a: string;
        /**
         * B
         */
        b: string;
    };
    url: '/api/edhrec/compare';
};

export type CompareErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareError = CompareErrors[keyof CompareErrors];

export type CompareResponses = {
    /**
     * Successful Response
     */
    200: CompareOut;
};

export type CompareResponse = CompareResponses[keyof CompareResponses];

export type CollectionFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/collection/families';
};

export type CollectionFamiliesResponses = {
    /**
     * Response Collection Families
     *
     * Successful Response
     */
    200: Array<FamilyOption>;
};

export type CollectionFamiliesResponse = CollectionFamiliesResponses[keyof CollectionFamiliesResponses];

export type CollectionData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Families
         */
        families: Array<string>;
    };
    url: '/api/collection';
};

export type CollectionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionError = CollectionErrors[keyof CollectionErrors];

export type CollectionResponses = {
    /**
     * Successful Response
     */
    200: CollectionOut;
};

export type CollectionResponse = CollectionResponses[keyof CollectionResponses];

export type CollectionBuyListData = {
    body: BuyListIn;
    path?: never;
    query?: never;
    url: '/api/collection/buy-list';
};

export type CollectionBuyListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CollectionBuyListError = CollectionBuyListErrors[keyof CollectionBuyListErrors];

export type CollectionBuyListResponses = {
    /**
     * Successful Response
     */
    200: BuyListOut;
};

export type CollectionBuyListResponse = CollectionBuyListResponses[keyof CollectionBuyListResponses];

export type DeckListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/decks';
};

export type DeckListResponses = {
    /**
     * Response Deck List
     *
     * Successful Response
     */
    200: Array<DeckSummaryOut>;
};

export type DeckListResponse = DeckListResponses[keyof DeckListResponses];

export type DeckDetailData = {
    body?: never;
    path: {
        /**
         * Slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/decks/{slug}';
};

export type DeckDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeckDetailError = DeckDetailErrors[keyof DeckDetailErrors];

export type DeckDetailResponses = {
    /**
     * Successful Response
     */
    200: DeckDetailOut;
};

export type DeckDetailResponse = DeckDetailResponses[keyof DeckDetailResponses];

export type CardHoldingsData = {
    body?: never;
    path: {
        /**
         * Scryfall Id
         */
        scryfall_id: string;
    };
    query?: never;
    url: '/api/cards/{scryfall_id}/holdings';
};

export type CardHoldingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CardHoldingsError = CardHoldingsErrors[keyof CardHoldingsErrors];

export type CardHoldingsResponses = {
    /**
     * Successful Response
     */
    200: HoldingsOut;
};

export type CardHoldingsResponse = CardHoldingsResponses[keyof CardHoldingsResponses];

export type IngestSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/ingest/search';
};

export type IngestSearchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestSearchError = IngestSearchErrors[keyof IngestSearchErrors];

export type IngestSearchResponses = {
    /**
     * Successful Response
     */
    200: SearchOut;
};

export type IngestSearchResponse = IngestSearchResponses[keyof IngestSearchResponses];

export type IngestResolveData = {
    body: ResolveIn;
    path?: never;
    query?: never;
    url: '/api/ingest/resolve';
};

export type IngestResolveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestResolveError = IngestResolveErrors[keyof IngestResolveErrors];

export type IngestResolveResponses = {
    /**
     * Successful Response
     */
    200: ResolveOut;
};

export type IngestResolveResponse = IngestResolveResponses[keyof IngestResolveResponses];

export type IngestCommitData = {
    body: CommitIn;
    path?: never;
    query?: never;
    url: '/api/ingest/commit';
};

export type IngestCommitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestCommitError = IngestCommitErrors[keyof IngestCommitErrors];

export type IngestCommitResponses = {
    /**
     * Successful Response
     */
    200: CommitOut;
};

export type IngestCommitResponse = IngestCommitResponses[keyof IngestCommitResponses];

export type IngestPreconsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/ingest/precons';
};

export type IngestPreconsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestPreconsError = IngestPreconsErrors[keyof IngestPreconsErrors];

export type IngestPreconsResponses = {
    /**
     * Response Ingest Precons
     *
     * Successful Response
     */
    200: Array<PreconOptionOut>;
};

export type IngestPreconsResponse = IngestPreconsResponses[keyof IngestPreconsResponses];
